package.json, pnpm-lock.yaml
=> Nightly Audit on 04/13/22

.github/workflows/release.yml
=> DB-1868: Fix workflow

starters/next-drupal-starter/.env.example
The name of this variable changed, so this needs to be updated too, correct?
=> Update IMAGE_DOMAIN Variable in .example.env

web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
---
name: Pull Request
about: Open a Pull Request
---
Updated drupal build tools install command
Minor markdown change.
=> DB-1609: update drupal build tools install command

package.json, pnpm-lock.yaml
=> Nightly Audit on 04/29/22

.circleci/config.yml, .github/workflows/release.yml, .husky/pre-commit, CONTRIBUTING.md, README.md, package.json, packages/drupal-kit/package.json, pnpm-lock.yaml
Upgrade pnpm to version 7.1.0 and fix --filter commands that were broken
decoupled-kit-js
tested commands and pre-commit hooks. CI will be run on this PR and will check if it passed.
=> DB-2794: Upgrade pnpm to 7.1.0

starters/next-drupal-starter/components/grid.js
=> DB-2339: Fix props for GridedComponent

.github/workflows/release-and-split.yml
Remove shameful dash from the GitHub workflow
=> DB-2818: Fix GH action

.changeset/dirty-geese-buy.md, packages/drupal-kit/package.json, pnpm-lock.yaml, starters/next-drupal-starter/pages/articles/[...slug].js, starters/next-drupal-starter/pages/pages/[...alias].js, starters/next-drupal-starter/pages/recipes/[...slug].js
- Upgrade drupal-state to latest version
- Utilize new refresh option from drupal-state to fetch fresh data from Drupal if a preview is requested.
drupal-kit
locally - tested previewing multiple revisions and I was able to see them without restarting the application.
=> Drupal state upgrade

web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md, web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md, web/docs/Packages/drupal-kit/classes/src_PantheonDrupalState.default.md, web/docs/Packages/drupal-kit/interfaces/src_types_types.authInit.md, web/docs/Packages/drupal-kit/modules/src_fetch_defaultFetch.md, web/docs/Packages/drupal-kit/modules/src_utils_addSurrogateKeyHeader.md, web/docs/Packages/drupal-kit/modules/src_utils_updateMaxAge.md, web/docs/Packages/wordpress-kit/classes/src_lib_ApolloClientFactory.default.md
Added note about the `--org` option, cleaned up some headings and made the command multiline. (do we need the \ at the end of the line of is that a windows thing?)
web/docs
=> Update build tools docs

web/docs/Frontend Starters/Next Drupal/setting-environment-variables.md
Removed some info that is not suited for the documentation living here. Fixed some spelling and formatting. 
docs
=> DB-2219: Refine next env var docs

.changeset/eight-spiders-punch.md, starters/next-wordpress-starter/components/grid.js, starters/next-wordpress-starter/lib/Pages.js, starters/next-wordpress-starter/pages/pages/index.js
- Added the file Pages.js to the lib, that has the function to query the latest pages
- Added the PageGridItem component to render a page
- Added the PagesGrid to the /pages route
Next-Wordpress-Starter
Tested locally and build, also I created a Page with a featured image in the wordpress to test that behavior, after that I deleted it, if is necessary I can keep it
=> DB-3180: Page Grid Page

package.json, pnpm-lock.yaml
=> Nightly Audit on 07/25/22

web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
Installation instructions as per ticket - https://getpantheon.atlassian.net/browse/DB-3023
Using Markdown editor
Related tickets to refer to -- 
https://getpantheon.atlassian.net/browse/DB-3259
https://getpantheon.atlassian.net/browse/DB-3020
=> DB-3023: Changing the project installation. for composer managed backend

.changeset/bright-donuts-shop.md, packages/wordpress-kit/src/lib/TailwindcssPlugin.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/Constants.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Image.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/PullQuote.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Quote.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Table.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Colors.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Fonts.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/index.ts, packages/wordpress-kit/src/types/TailwindcssPlugin.d.ts
- Added support to gradient backgrounds
- Moved the utilities to separated files
- wordpress-kit
- Tested all the utilities
- Tested gradients
=> DB-3609: Block Editor Gradients

.changeset/cold-years-protect.md, starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/default/articles.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/default/auth-api.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/default/examples-index.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/default/pages.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/default/pagination.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/default/ssr-isr-example.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/articles.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/auth-api.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/examples-index.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/pages.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/pagination.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/recipes.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/ssr-isr-example.test.jsx.snap, starters/next-drupal-starter/__tests__/snapshotTests/examples-index.test.jsx, starters/next-drupal-starter/__tests__/snapshotTests/ssr-isr-example.test.jsx, starters/next-drupal-starter/pages/examples/ssg-isr.jsx
=> Recreating DB-3594: snapshot tests - to test CI

.changeset/metal-apples-talk.md, starters/next-drupal-starter/__tests__/__snapshots__/default/auth-api.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/auth-api.test.jsx.snap, starters/next-drupal-starter/pages/examples/auth-api.jsx
- Fix missing import in `pages/examples/auth-api.jsx`
- Also updated some formatting for that route
locally
=> DB-3593: Fix import

.changeset/ten-monkeys-remain.md, packages/wordpress-kit/src/lib/TailwindcssPlugin.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Audio.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
- Added Audio component to the tailwind plugin
- Next-WP Starter
- Locally
=> DB-3652: Block Editor Audio Styles

.github/workflows/canary-sites-split.yml
- Fix workflow name
`.github/workflows`
=> DB-3678: Fix workflow name

.changeset/pre.json
=> Re-enter pre-mode

.changeset/brown-taxis-pretend.md
Add changeset for paginator component
=> DB-3604: Add changeset

web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
Minor documentation update.
Based on feedback from onboarding team.
=> Update terminus site:create command for WordPress.

.changeset/perfect-dragons-rescue.md, packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/Constants.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/MediaAndText.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Colors.ts
- Added support to Media Text block
- Fixed text color on bold
- Locally
if needed!
=> DB-3656: Block Editor Media and Text Block Styles

.changeset/pre.json
Exit prerelease mode
if needed!
=> Sprint 32 exit prerelease mode

.changeset/swift-years-wait.md, packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Buttons.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/FileMedia.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/shared/Button.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/shared/index.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts
- Added File block support
- Added general button styles
- Used those styles on buttons block
- Locally
if needed!
=> DB-3655: Add file block

.changeset/pre.json
Existing pre-release mode for final sprint 33 release.
=> Sprint 33 exit pre release mode

.changeset/pre.json
=> Enter pre-release mode for sprint 34

.husky/pre-commit
- Added exit when CI env is set up
- decoupled-kit
=> DB-2834: Automatically Husky Install

web/docs/Frontend Starters/Next.js/Next.js + Drupal/troubleshooting-local-development.md, web/docs/Frontend Starters/Next.js/Next.js + Drupal/troubleshooting.md
- Add a Troubleshooting Local Development doc
docs
=> DB-2625: [next-drupal-starter] Document common issues

web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md
Added a doc for troubleshooting common issues with the gatsby-wordpress-starter
n/a
=> DB-2624: Document gatsby-wp common trobuleshooting

web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
Added a document that goes over common troubleshooting with the next-wordpress-starter
n/a
=> DB-4534: [next-wordpress-starter] Add doc troubleshooting docs

CODEOWNERS
Add CODEOWNERS file with the correct team name.
In the root of the project.
=> DB-2366: Add CODEOWNERS file.

.changeset/pre.json
=> Sprint 35 - enter prerelease

.changeset/afraid-dingos-dream.md, .changeset/tender-students-occur.md, packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/contentWithImage.test.tsx.snap, packages/nextjs-kit/src/components/contentWithImage.tsx, packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Audio.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Buttons.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Cover.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/FileMedia.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Gallery.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Image.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/MediaAndText.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/PullQuote.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Quote.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Table.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Video.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/shared/Alignment.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/shared/index.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Base.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/index.ts, starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/default/articles.test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap, starters/next-drupal-starter/__tests__/__snapshots__/umami/articles.test.jsx.snap, starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pages.test.jsx.snap, starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/posts.test.jsx.snap, starters/next-wordpress-starter/pages/pages/[uri].jsx, starters/next-wordpress-starter/pages/posts/[slug].jsx
Reverts pantheon-systems/decoupled-kit-js#362
@enZane This un-reverts the Block Editor alignment work. I'm assuming this will need additional refinements / a new changeset.
=> WIP Revert "Revert "DB-4060: Block Editor Alignment Options""

.changeset/brown-eels-tap.md, packages/wordpress-kit/src/lib/tailwindcssPlugin/components/shared/Alignment.ts, packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Base.ts
- Adds media queries to follow the actual implementation of the layout
- WP-Kit
Locally, reviewed contrasting against Drupal
=> DB-4060: Block Editor Alignment Options

.github/scripts/with-commit.sh, .github/workflows/canary-release.yml, .github/workflows/canary-repo-split.yml, .github/workflows/main-release.yml, .github/workflows/main-repo-split.yml, .github/workflows/release-job.yml
Reverts pantheon-systems/decoupled-kit-js#381
Adds proper account to with-commit script
=> DB-4593: [ci] Add with-commit script, refactor some GH actions 

.changeset/pre.json
=> Exit prerelease for sprint 35

.changeset/pre.json
=> Enter prerelease mode for sprint 36

.changeset/small-geckos-turn.md, web/docs/Frontend Starters/Next.js/Next.js + WordPress/styling-configuration.md
- Adds documentation for theming front-end site
- Documentation
=> DB-2839: Updating Theming

web/docs/Frontend Starters/Next.js/Next.js + Drupal/styling-configuration.md, web/docs/Frontend Starters/Next.js/Next.js + WordPress/styling-configuration.md
- Adds docs for styling on Next + Drupal starter
- Web
=> DB-2840: Updating Theming Docs

.changeset/pre.json
=> Exit prerelease mode - Sprint 36

.changeset/pre.json
=> Enter prerelease mode for sprint 37

web/docusaurus.config.js, web/src/pages/index.js
Adding some global keywords and a little tweak to title/description. Next step would be to find a nice image and do some social platform specific tweaking, but I ran out of time.
=> Tweaking the meta

web/docs/decoupled-kit-overview.md
Removed extra line inside an example command
https://decoupledkit.pantheon.io/docs/decoupled-kit-overview
Not tested.
_I'm not sure if this is needed._
=> Remove extra line

.github/workflows/canary-release.yml, .github/workflows/release-and-split.yml
=> Update node-setup version to v3

.github/workflows/canary-release.yml, .github/workflows/release-and-split.yml
Updated our release actions to setup node and pnpm as shown in the latest pnpm docs
This should also give us proper caching out of the box. 
Successful dry run of the action ran locally with https://github.com/nektos/act
=> Update release workflows to use pnpm/action-setp

.changeset/pre.json
=> Sprint 37 exit prerelease mode

.changeset/pre.json
=> Sprint 38 enter prerelease mode

web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
- Explain limitation of previewing drafts in our next+Drupal docs
=> DB-4395: [docs] Add doc regarding limitation of previewing drafts in Drupal

.changeset/pre.json
=> Exit pre-release mode for sprint 38

.changeset/pre.json
=> Enter pre-release for sprint 39

package.json, pnpm-lock.yaml
=> Nightly Audit on 12/31/22

.changeset/pre.json
=> Enter pre-release mode for sprint 2

web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md, web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
Added a new Documentation for Configuring Drupal Preview site.
=> DB-2799: Documentation for Configuring Drupal Preview site.

web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-environment-variables.md
=> DB-5281: Typo update

package.json, pnpm-lock.yaml
=> Nightly Audit on 01/25/23

.changeset/pre.json
=> Exit pre-release for sprint 2

.github/workflows/canary-sites-split.yml, .github/workflows/release-and-split.yml
=> Upgrade to latest monorepo split action release

.github/workflows/canary-sites-split.yml, .github/workflows/release-and-split.yml
=> Update monorepo split version and commit username

.github/workflows/canary-sites-split.yml, .github/workflows/release-and-split.yml
=> Correct the tag reference for monorepo split action

.changeset/pre.json
=> Enter prerelease mode for sprint 3

package.json, pnpm-lock.yaml
=> Nightly Audit on 02/02/23

.changeset/pre.json
Exited pre-release mode to trigger changeset release.
=> Exit pre-release mode for sprint 3

.changeset/pre.json
=> Enter pre-release for sprint 4

web/docs/Backend Starters/Decoupled Drupal/caching-considerations.md, web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md, web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md, web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md, web/docs/Backend Starters/Decoupled Drupal/cors.md
Added Caching considerations entry under Drupal backend projects.
Docs
Ran docs site locally.
=> DB-4186: Document how to emit cache-control headers for caching API calls

web/docs/Backend Starters/Decoupled Drupal/caching-considerations.md, web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md, web/docs/Backend Starters/Decoupled WordPress/configuring-existing-project.md
* Added a Caching Considerations section in the WP BE Starter section.
* Cross linked caching considerations in 'Configuring an existing WP project'
* Minor editorial tweaks for Drupal caching entry for consistency.
Docs.
Ran docs site locally.
This entry is pretty closely related to [DB-5240](https://getpantheon.atlassian.net/browse/DB-5240), which will probably expand on this entry in a few ways.
[DB-5240]: https://getpantheon.atlassian.net/browse/DB-5240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DB-4187: Document how to emit cache-control headers for caching API calls

.changeset/pre.json
=> Enter pre-release mode for sprint 5

package.json, pnpm-lock.yaml
=> Nightly Audit on 02/10/23

.github/workflows/canary-sites-split.yml, .github/workflows/release-and-split.yml
Hopefully this fixes the GH Action conditional steps so that the docs site still works.
This should also be a good test of our most recent canary release of the CLI.
=> DB-5253: Fix for conditional action

.github/workflows/canary-sites-split.yml, .github/workflows/release-and-split.yml
Add the conditional statement to the `run` step as well
CI
Actions syntax 🥲 
=> DB-5253: Try to fix GH Action conditional

CONTRIBUTING.md, package.json, pnpm-lock.yaml, web/docs/Frontend Starters/Next.js/Next.js + Drupal/add-ons.md
The audit script has been failing (reason unknown). Hopefullythis will help it get working again.
monorepo, also fixed a typo in CONTRIBUTING.md and a broken link in the dev docs.
=> Dependency audit and some typo fixes

.changeset/pre.json
=> Exit pre-release mode for sprint 5

.changeset/pre.json
=> Enter pre-release for sprint 6

.changeset/fair-emus-accept.md, CONTRIBUTING.md, packages/create-pantheon-decoupled-kit/__tests__/index.test.ts, packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp-acf-addon.generator.ts, packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts, packages/create-pantheon-decoupled-kit/src/generators/index.ts, packages/create-pantheon-decoupled-kit/src/generators/next-drupal-search-api-addon.generator.ts, packages/create-pantheon-decoupled-kit/src/generators/next-drupal-umami-addon.generator.ts, packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts, packages/create-pantheon-decoupled-kit/src/generators/next-wp-acf-addon.generator.ts, packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts, packages/create-pantheon-decoupled-kit/src/generators/tailwindcss-addon.generator.ts, packages/create-pantheon-decoupled-kit/src/index.ts, packages/create-pantheon-decoupled-kit/src/types.ts, packages/create-pantheon-decoupled-kit/src/utils/helpMenu.ts
- Refactored the DecoupledKitGenerator type to take in an additional generic to describe the arbitrary data
- Refactored some types to get more strongly typed arbitrary data
- Add a detailed example to the CONTRIBUTING docs showing how to create a new generator with arbitrary data and extra prompts, and a template which uses all of the supplied data.
CONTRIBUTING.md
cli
ran the CLI and generated a few projects
=> DB-5060: refine contributing to cli docs and generator generics

.changeset/pre.json
=> Exit pre-release mode for sprint 6

.changeset/pre.json
=> Enter pre-release mode for sprint 7

.changeset/pre.json, .npmrc, packages/cms-kit/CHANGELOG.md, packages/cms-kit/package.json, packages/create-pantheon-decoupled-kit/CHANGELOG.md, packages/create-pantheon-decoupled-kit/package.json, packages/drupal-kit/CHANGELOG.md, packages/drupal-kit/package.json, packages/nextjs-kit/CHANGELOG.md, packages/nextjs-kit/package.json, packages/wordpress-kit/CHANGELOG.md, packages/wordpress-kit/package.json
=> Revert "Canary Release (canary)"

.changeset/pre.json
=> Exit pre-release mode for sprint 7

.changeset/pre.json
=> Enter prerelease mode for sprint 8

web/docs/Backend Starters/Decoupled Drupal/add-ons.md, web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md, web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md, web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md
Added a new section to Backend Starters → Decoupled Drupal as Add-on for the Decoupled Kit Pantheon Search API Module.
=> DB-5719: Add-on docs for Decoupled Kit Pantheon Search API module.

.changeset/dirty-rats-share.md, .changeset/olive-wolves-call.md
Fixes misapplied changeset and one typo 
=> Fix changesets

package.json, pnpm-lock.yaml
=> Nightly Audit on 04/25/23

.changeset/pre.json
=> Exit pre-release mode for sprint 8

.changeset/pre.json
=> Enter pre-release mode for sprint 9

packages/create-pantheon-decoupled-kit/README.md, web/docs/decoupled-kit-overview.md
Update this section to use the cli.
Add links to the API ref in the CLI readme
CLI readme, docs
Checked the links with the docs site running locally
=> Refactor overview doc section on creating a new starter

.changeset/pre.json
=> Exit pre-release mode for sprint 9

.changeset/pre.json
=> Enter pre-release more for sprint 10

.changeset/lovely-pants-sip.md, .changeset/polite-rats-behave.md, packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs, packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/nextDrupalPkgJson.hbs
Fix the prettier:fix command on `lint:fix`
=> Fix lint:fix command

.changeset/pre.json
=> Enter pre-release mode for sprint 11

.changeset/pre.json
=> Exit pre-release for sprint 11

.changeset/pre.json
=> Enter prerelease mode for sprint 12

.changeset/pre.json
=> Exit pre-release to release docs

web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
Added DrupalState code sample to surrogate key docs page.
Docs.
Running docusaurus locally.
=> DB-4189: add DrupalState code sample to surrogate key docs page

.changeset/pre.json
=> Exit pre-release mode for sprint 12

.changeset/pre.json
=> Enter pre-release mode for sprint 13

package.json, pnpm-lock.yaml
=> Nightly Audit on 06/23/23

.changeset/pre.json
=> Exit pre-release mode for sprint 13

.changeset/pre.json
=> Enter pre-release for sprint 14

.changeset/thirty-ligers-rule.md, packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
=> Fix next-wp package.json

.changeset/pre.json
=> Exit pre-release for sprint 15

.changeset/pre.json
=> Enter pre-release mode for sprint 16

.changeset/clever-chefs-exist.md, .changeset/happy-eggs-rescue.md, packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.env.example, packages/create-pantheon-decoupled-kit/src/templates/next-drupal/.env.example, packages/create-pantheon-decoupled-kit/src/templates/next-wp/.env.example, packages/decoupled-kit-health-check/__tests__/__snapshots__/NextWordPressHealthCheck.test.ts.snap, packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts
Added some explanation comments to the .env.examples
all 3 starters
n/a
=> DB-6233: Add comments to .env.example env vars

web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md, web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md, web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md, web/docs/Backend Starters/Decoupled Drupal/cors.md, web/docs/Backend Starters/Decoupled Drupal/local-development.md, web/docs/Backend Starters/Decoupled Drupal/updating-dependencies.md, web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md, web/docs/Backend Starters/Decoupled WordPress/configuring-build-hooks.md, web/docs/Backend Starters/Decoupled WordPress/configuring-existing-project.md, web/docs/Backend Starters/Decoupled WordPress/local-development.md, web/docs/Backend Starters/Decoupled WordPress/managing-dependencies.md, web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/add-ons.md, web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md, web/docs/Frontend Starters/Next.js/Next.js + Drupal/add-ons.md, web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md, web/docs/Frontend Starters/Next.js/Next.js + Drupal/troubleshooting.md, web/docs/Frontend Starters/Next.js/Next.js + WordPress/add-ons.md, web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md, web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
- Reorders some items in the navigation bar for consistency and to display higher priority information first.
`web`
locally
=> DB-5858: Audit Navigation Structure

.github/workflows/canary-release.yml, .github/workflows/release-and-split.yml
Explicitly set the @pantheon-decoupled-service-user as the git user
=> CI: Attempt to fix changeset action #2

.github/workflows/canary-release.yml, .github/workflows/release-and-split.yml
=> CI: Revert ci fix attempts

.github/workflows/canary-release.yml, .github/workflows/release-and-split.yml
Trying again on setting explicit permissions
=> CI: Set pull-requests and contents permissions to write

.changeset/pre.json
=> Exit pre-release for belated sprint 16

.changeset/pre.json
=> Enter prerelease for sprint 17

packages/create-pantheon-decoupled-kit/src/templates/partials/shared/readme/sharedReadme.ts
=> DB-6235: Use correct images for the theme context

.changeset/pre.json
=> Exit prerelease for sprint 17

.changeset/pre.json
=> Enter pre-release for sprint 18

.changeset/pre.json
=> Exit prerelease mode for sprint 18

.changeset/pre.json
=> Enter pre-release for sprint 19

.changeset/pre.json
=> Exit pre-release mode for sprint 19

.changeset/pre.json
=> Enter pre-release for sprint 20

.github/actions/setup-node/action.yml, .github/workflows/canary-sites-split.yml
BOOleans aren't working as expected: https://github.com/actions/runner/issues/1483 👻
ci
=> KIT-46: Use string instead of fake boolean

.github/workflows/canary-sites-split.yml
=> KIT-46: Fix typo

.github/workflows/cli-addon-tests.yml
Should fix the upload path for the ci tests, if not some more investigation will be required.
headless regression test workflow
=> KIT-67: Fix upload path

.github/workflows/snapshot-release.yml
=> KIT-126: Remove provenance

.github/workflows/snapshot-release.yml
The tag name was not being picked up causing the publish to go to the wrong tag.
=> KIT-126: Fix tag

web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md, web/docs/Backend Starters/Decoupled Drupal/creating-a-new-project.mdx, web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
Updated our docs as needed so that it reflects that changes introduced with the Drupal FTUE work.
`web/docs`
Locally
=> KIT-25: Drupal FES Settings Developer Docs

.changeset/big-keys-live.md, .changeset/shy-toys-know.md
Adds changesets for previous work in KIT-63
.changeset
=> KIT-63: Add Changesets For Health Check Updates

.changeset/pre.json
=> Enter pre-release mode for sprint 24

web/docs/Backend Starters/Decoupled Drupal/creating-a-new-project.mdx
=> Update Drupal BE docs to clarify Umami Demo is a standalone dependency

.changeset/pre.json
=> Enter pre-release mode

.changeset/pre.json
=> Enter pre-release mode for Feb 2024

.changeset/pre.json
=> Enter Pre-release for March Release

.changeset/pre.json
=> Enter Pre-release for April Release
