pantheon-systems/decoupled-kit-js

.changeset/sweet-eggs-call.md
starters/next-drupal-starter/lib/constants.js
starters/next-drupal-starter/next.config.js
starters/next-drupal-starter/package.json
starters/next-drupal-starter/pages/articles/[...slug].js
starters/next-drupal-starter/pages/articles/index.js
starters/next-drupal-starter/pages/examples/pagination/[[...page]].js
starters/next-drupal-starter/pages/index.js
starters/next-drupal-starter/pages/pages/index.js
starters/next-drupal-starter/pages/recipes/[...slug].js
starters/next-drupal-starter/pages/recipes/index.js

- Added  `/lib/constants.js` file that contains the single-source of truth for relevant env vars consumed by pages & components
- Added logic to allow an empty BACKEND_URL to fallback to PANTHEON_CMS_ENDPOINT which should prevent builds from failing if this variable is not set when creating a new site.
- Added logic to determine the IMAGE_DOMAIN from the BACKEND_URL or PANTHEON_CMS_ENDPOINT, and will take the value of IMAGE_DOMAIN if it exists.

DB-2114: [next-drupal] Refine environment variable config

---

.changeset/forty-bikes-lick.md
starters/gatsby-wordpress-starter/gatsby-config.js

- Gatsby will now fallback to the `PANTHEON_CMS_ENDPOINT` if a `WPGRAPHQL_URL` is not provided

DB-2115: [gatsby-wordpress] Refine environment variable config

---

web/docs/Frontend Starters/Gatsby Wordpress/setting-environment-variables.md

Adds documentation regarding setting environment variables for the `gatsby-wordpress-starter` both locally and in multi-dev environments.
Not sure we need/want a changeset for this, lmk if we do.

DB-1467: [docs] Gatsby Starter Environment Variable Configuration

---

.changeset/thirty-chairs-compete.md
starters/next-drupal-starter/.gitignore
starters/next-drupal-starter/next.config.js
starters/next-drupal-starter/package.json

According to [Next.js env variable load order](https://nextjs.org/docs/basic-features/environment-variables#environment-variable-load-order), `.env.local` is loaded in production environments.  To avoid this, I've changed the local .env file to `.env.development.local` which will not be loaded in production environments.

DB-2114: [next-drupal] Fix .env.local loading in production

---

.changeset/friendly-cars-jump.md
.changeset/thirty-chairs-compete.md
starters/next-drupal-starter/.env.example
starters/next-drupal-starter/CHANGELOG.md
starters/next-drupal-starter/README.md
starters/next-drupal-starter/next.config.js
starters/next-drupal-starter/package.json

It seems Next.js loads some .env files in production.
- Remove the postinstall script so we don't have to worry about .env files in prod
- Update README with instructions on creating a `.env.development.local` file

DB-2114: [next-drupal] Remove postinstall script

---

.changeset/fast-rules-occur.md
starters/next-drupal-starter/next.config.js
starters/next-drupal-starter/pages/articles/[...slug].js
starters/next-drupal-starter/pages/index.js
starters/next-drupal-starter/pages/pages/[alias].js
starters/next-drupal-starter/pages/pages/index.js
starters/next-drupal-starter/pages/recipes/[...slug].js
starters/next-drupal-starter/pages/recipes/index.js

Previously this was done in the .env file but it makes sense to move it to the config. Currently setting FRONTEND_URL won't have the intended effect, but this change should make it work.
- Strip trailing slash from FRONTEND_URL and set it to NEXT_PUBLIC_FRONTEND_URL
- Uses NEXT_PUBLIC_FRONTEND_URL for setting the hrefLang to avoid double slashes

[next-drupal] Expose Next FRONTEND_URL

---

.changeset/wicked-vans-design.md
packages/drupal-kit/package.json
packages/drupal-kit/src/PantheonDrupalState.ts
packages/drupal-kit/src/__tests__/PantheonDrupalState.test.ts
pnpm-lock.yaml
starters/next-drupal-starter/package-lock.json

- Upgrade `@gdwc/drupal-state` to version 2.6.0
- Generate new package-lock for `next-drupal-starter`
- Update constructor and add a test for `PantheonDrupalState` in `drupal-kit`
`drupal-kit`, `next-drupal-starter`, `decoupled-kit-js`
Tested changes locally & added a test to `drupal-kit`
Please double check my changeset. I'm not sure if these should both be patches or minor versions or if it's fine as is.

Chore: Upgrade DrupalState

---

starters/next-drupal-starter/README.md
starters/next-drupal-starter/pages/recipes/[...slug].js
starters/next-drupal-starter/pages/recipes/index.js

Added comments and some documentation regarding the safe removal of `pages/recipes` if the Drupal backend is not sourcing Umami data
n/a
The work to prevent builds from failing if there is no recipe data was done in DB-2113

DB-2719: Document removal of recipes pages

---

.github/workflows/release-and-split.yml

Make the GitHub Actions workflow jobs run sequentially instead of in parallel
https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs

DB-2818: Run packages_split job after version

---

starters/gatsby-wordpress-starter/gatsby-config.js

Document how to reduce concurrency for gatsby-source-wordpress
in case the WordPress server is overloaded
Added a comment and commented out options for reducing concurrent requests made by gatsby-source-wordpress in case the WordPress server is being overloaded.
gatsby-wordpress-starter
@backlineint Willing to add a proper doc to the documentation if needed, but I wasn't sure it was necessary here at this time.

DB-2793: Add note and options to reduce concurrency for gatsby-source-wordpress

---

pnpm-lock.yaml
starters/next-drupal-starter/package-lock.json
starters/next-drupal-starter/package.json

Removed `next-absoulte-url`
locally and on the platform

DB-2235: Remove `next-absolute-url`

---

web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
web/docs/Packages/wordpress-kit/classes/src_lib_ApolloClientFactory.default.md

Added additional doc for git hosts or CI services example flags commands.
Docusaurus docs

DB-2864: Added additional doc for git hosts or CI services example flags.

---

.changeset/mighty-pianos-bow.md
starters/next-drupal-starter/lib/getPaths.js
starters/next-drupal-starter/pages/articles/[...slug].js
starters/next-drupal-starter/pages/examples/auth-api.js
starters/next-drupal-starter/pages/examples/pagination/[[...page]].js
starters/next-drupal-starter/pages/pages/[...alias].js
starters/next-drupal-starter/pages/pages/index.js
starters/next-drupal-starter/pages/recipes/[...slug].js
web/docs/Frontend Starters/Next Drupal/implementing-preview.md

- Added a helper function to DRY up getStaticPaths
- Implemented the helper
- Small change to these routes to use the authStore if preview is true, otherwise use the non auth'd store. This should allow builds to succeed even if credentials are incorrect.
tested builds locally

DB-2295: Create helper for getStaticPaths

---

.github/workflows/canary-sites-split.yml

GitHub Action workflow added that runs on pushes to the canary branch. This will mirror the starter for each push to canary so it will be available to QA on.
We could configure the workflow we already have and do some fancy logic to build the strategy matrix based on the branch, but I think this is more straightforward although perhaps bit clunkier.
added a new workflow in `.github/workflows`

DB-1020: Create canary site for next-drupal-starter

---

.github/workflows/canary-sites-split.yml

Add another canary repo split, this one for the `gatsby-wordpress-starter` using the default demo profile
decoupled-kit-js GitHub action

DB-2109: Add a canary repo split for `gatsby-wordpress-starter`

---

.github/workflows/canary-sites-split.yml

Adding another canary site, this time for the default Drupal install profile.
decoupled-kit

DB-2241: Add canary split for next-drupal with default data

---

.changeset/dull-experts-provide.md
starters/next-drupal-starter/lib/getPaths.js
starters/next-drupal-starter/pages/pages/[...alias].js
starters/next-drupal-starter/pages/pages/index.js

- Make urlAliasPrefix optional in the regex in `getPaths` to handle content that is not prefixed like pages.
- Handle cases where some pages could be prefixed with `/pages` and some are not.
- Update the href locale in `pages/[...alias]` to fallback to the router locale if the `page.path.langcode` is undefined.
Locally

DB-2278: Fix regressions with 'page' paths

---

.changeset/good-mugs-brake.md
starters/next-drupal-starter/lib/getPreview.js
starters/next-drupal-starter/pages/articles/[...slug].js
starters/next-drupal-starter/pages/pages/[...alias].js
starters/next-drupal-starter/pages/recipes/[...slug].js

- `getPreview` helper only fetches preview data if NOT preview a revision, as revisions do not use the `decoupled_preview/` endpoint.
- Use the `refresh` parameter to force fetch to Drupal when previewing a revision in `getStaticProps` for previewable content.
Tested locally

DB-3315: Fix preview revisions

---

.changeset/calm-mails-attack.md
.changeset/good-mugs-brake.md
starters/next-drupal-starter/lib/getPreview.js
starters/next-drupal-starter/package-lock.json
starters/next-drupal-starter/pages/api/preview.js
starters/next-drupal-starter/pages/articles/[...slug].js
starters/next-drupal-starter/pages/pages/[...alias].js
starters/next-drupal-starter/pages/recipes/[...slug].js

‼️ To be merged AFTER #168
Update the `/api/preview` route to use the objectName that is now provided in the `req.query`.
This allows us to remove some highly assumptive regex for getting the proper objectName.
Tested preview from umami profile and default profile. Paths

DB-2876: Use `req.query.objectName` in preview api route

---

.changeset/friendly-shoes-hear.md
.changeset/unlucky-bats-tickle.md
packages/wordpress-kit/index.ts
packages/wordpress-kit/package.json
packages/wordpress-kit/rollup.config.js
packages/wordpress-kit/src/lib/tailwindcssPlugin.ts
pnpm-lock.yaml
starters/next-wordpress-starter/tailwind.config.js

- Added a plugin to WordPress-kit that extends the classes to map styles that comes from the WordPress block editor
- WordPress-kit
- Next-WordPress Starter
- Locally and built

DB-3184: Enhanced Block Editor Support - Paragraph Block POC

---

.github/workflows/release-and-split.yml

Like our other starters, this change will make the `next-wordpress-starter` available at https://github.com/pantheon-systems/next-wordpress-starter for easy cloning and using with `create-next-app`.
decoupled-kit, ci

DB-3183: Split next-wordpress-starter to standalone repo in ci

---

.changeset/lazy-poets-count.md
package.json
pnpm-lock.yaml
starters/gatsby-wordpress-starter/package-lock.json
starters/gatsby-wordpress-starter/package.json

Downgrade back to gatsby 4.16.0 as there is some unknown issue when using `placeholder: TRACED_SVG`.
starter builds locally

Downgrade gatsby@4.19.0 to 4.16.0

---

.github/workflows/canary-sites-split.yml

Add the `next-wordpress-starter` to the canary-sites-split workflow. Expediting this a bit so that we can get a stable domain on it sooner than later. 
changes to GitHub action workflow
n/a

DB-3188: Add next-wordpress-starter canary site

---

.changeset/soft-lemons-draw.md
packages/wordpress-kit/src/lib/tailwindCssPlugin/config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin.ts

- Added text-alignment behavior to the utility classes
- Added empty quotes and border movement to quotes depending of the text alignment
- wordpress-kit
- Locally and built

DB-3466: Rendering issues for quote blocks for wordpress-next starter site

---

.changeset/neat-frogs-dress.md
starters/next-wordpress-starter/components/footer.jsx
starters/next-wordpress-starter/lib/Menus.js

- Added a formatter to the lib/Menus.js that take the URI and returns the pathname, and is applied when the URI starts with HTTP to fix the console error
- next-wordpress-starter
- locally and built
- with the older QA WP site and the new with WP6

DB-3453: [next-wordpress] Invalid href passed to next/router

---

.changeset/five-rings-compare.md
packages/wordpress-kit/src/lib/tailwindcssPlugin.ts

- Fixed a problem that overflow text very close to the right border
- wordpress-kit
- Locally

DB-3466: Fix a problem with the spacing inside the pullquotes

---

.changeset/calm-years-lick.md
packages/wordpress-kit/src/lib/tailwindCssPlugin/config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin.ts
packages/wordpress-kit/src/types/tailwindcssPlugin.d.ts
starters/next-wordpress-starter/components/post.jsx

- Added styles to render tables
- Wordpress-kit
- Locally
- I'm not sure about the block alignment, because in the WP block editor it looks broken 
but is in the PR, if we decide to don't honor it, then I can remove that behavior

DB-3466: Add table styles

---

.changeset/curvy-birds-wink.md
packages/wordpress-kit/src/lib/tailwindCssPlugin/constants.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin.ts
packages/wordpress-kit/src/types/tailwindcssPlugin.d.ts

- Change default theme colors to follow WP6 styles
- Fix on border styles for tables
- Wordpress-kit
- Locally

DB-3467: Add table styles

---

.eslintrc
package.json
packages/nextjs-kit/.eslintrc
packages/nextjs-kit/.gitignore
packages/nextjs-kit/README.md
packages/nextjs-kit/package.json
packages/nextjs-kit/rollup.config.js
packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/test.test.tsx.snap
packages/nextjs-kit/src/__tests__/snapshotTests/test.test.tsx
packages/nextjs-kit/src/__tests__/testLib.test.ts
packages/nextjs-kit/src/components/test.tsx
packages/nextjs-kit/src/components/test2.tsx
packages/nextjs-kit/src/index.ts
packages/nextjs-kit/src/lib/testLib.ts
packages/nextjs-kit/tsconfig.json
packages/nextjs-kit/umd-entrypoint.ts
packages/nextjs-kit/utils/getFiles.js
packages/nextjs-kit/vite.config.js
pnpm-lock.yaml
tsconfig.json

Created a new package 🥳 
- new `nextjs-kit` in `packages` workspace
- Uses codesplitting & submodules for ESModules
- Also supports UMD module
- Components use default exports, lib uses named exports 
`nextjs-kit`
Tests have been added for some barebones test components/lib function.
The components and function were imported into the `next-drupal-stareter` as well.
Should we make the package.json version 0.0.0 and add a changeset? Or keep it how it is with no changeset?

DB-3603: Initialize the nextjs-kit

---

.changeset/many-months-matter.md
.changeset/strange-carrots-divide.md
packages/drupal-kit/package.json
pnpm-lock.yaml
starters/next-drupal-starter/lib/getPreview.js
starters/next-drupal-starter/pages/[...alias].jsx
starters/next-drupal-starter/pages/articles/[...slug].jsx
starters/next-drupal-starter/pages/pages/[...alias].jsx
starters/next-drupal-starter/pages/recipes/[...slug].jsx

Changes to update starter kit to use drupal-state version 3.1.0
Yes, by modifying the starter kit pages/articles/index.jsx and adding console logs to get different drupal-state entries for fetches on same object with different query parameters

DB-3479: Upgrade DrupalState to 3.1.0

---

starters/next-wordpress-starter/next.config.js

Updated config logic so that importing a site made with the next-wordpress-starter into the dashboard and linking a cms results in a successful build without setting any env vars.
next-wordpress-starter
Successfully deployed a site using the next-wordpress-starter without setting any environment variables.

DB-3597: [next-wordpress] Automatic CMS config

---

.changeset/eight-emus-trade.md
packages/wordpress-kit/src/lib/TailwindcssPlugin.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Gallery.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts

- Added support for Gallery block
- Wordpress-kit
- Locally

DB-3651: [next-wordpress] Block Editor Gallery Styles

---

.changeset/cuddly-terms-explode.md
starters/next-wordpress-starter/lib/WordPressClient.js
starters/next-wordpress-starter/lib/WordpressClient.js

GitHub doesn't respect changing case of a filename unless you commit the deletion of the file, then recommit it as a 'new file'. It seems to understand the rename after that. 🙃
TBD on our canary site

Fix next wp starter

---

.changeset/pre.json

Exits prerelease mode, which I believe would trigger a standard release when we merge to main.
I did a local dry run of `changeset version` on this branch and the diff made sense to me, - I'll share in slack.

Sprint 30 - Exit prerelease mode

---

.changeset/four-pans-protect.md
starters/next-drupal-starter/next.config.js
starters/next-wordpress-starter/next.config.js

If using `http` for the `BACKEND_URL` in either Next.js starter, the image domain would add `https` to the begining of the url and break all images. This should make it so if a user does not set the `IMAGE_DOMAIN` and is using `http` for the `BACKEND_URL` or `WPGRAPHQL_URL`, things will not break.
`next-drupal-starter`, `next-wordpress-starter`
tested locally

Remove protocol from `IMAGE_DOMAIN` if it is http OR https

---

.changeset/gentle-pumas-compare.md
packages/wordpress-kit/src/lib/TailwindcssPlugin.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Cover.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Colors.ts

- Added support for Cover component
- Locally

DB-3654: Block Editor Cover Styles

---

.changeset/gold-avocados-end.md
starters/next-drupal-starter/pages/api/preview.js

The `next-drupal-starter` was not building due to a borked import. Somehow it got changed in the prettier config pr.

Fix import

---

.changeset/pre.json

Exit sprint-31 pre-release

---

.changeset/small-eggs-work.md
packages/nextjs-kit/package.json
packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/contentWithImage.test.tsx.snap
packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/footer.test.tsx.snap
packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/header.test.tsx.snap
packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/paginator.test.tsx.snap
packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/recipe.test.tsx.snap
packages/nextjs-kit/src/components/contentWithImage.tsx
packages/nextjs-kit/src/components/footer.tsx
packages/nextjs-kit/src/components/header.tsx
packages/nextjs-kit/src/components/paginator.tsx
packages/nextjs-kit/src/components/recipe.tsx
packages/nextjs-kit/tailwind.config.js
pnpm-lock.yaml
starters/next-drupal-starter/__tests__/__snapshots__/default/pagination.test.jsx.snap
starters/next-drupal-starter/__tests__/__snapshots__/umami/pagination.test.jsx.snap

- Add the `prefix` option to the tailwindcss config
- Refactor all tailwindcss classes to add the prefix
- Also took this opportunity to refactor the Paginator component a bit and increase the accessibility with proper aria labels, a nav container, and `ul>li` markup. 
- Added the eslint-prettier plugin to the nextjs kit since the lint step complains when I do not have it as a dev dependency.
`nextjs-kit`, updated snapshot tests for the pagination component in `next-drupal`
Locally w/ a screen reader
Going forward we will need to use `ps-` for all tailwind styles in the nextjs-kit. We should follow suit for any other libraries that export components. (Will ps- work for all of them, what if you import from 2 libraries with ps-, will it break?)
There is some significant effort to switch the …

DB-4217: Add tailwindcss prefix

---

.changeset/shaggy-walls-talk.md
packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Buttons.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Colors.ts

- Added button component
- Added getColorByName to the color class
- With Next-WP-Starter
- Looks like alignment is bugged from WP, doesn't work on WP preview, and doesn't add any class to the produced HTML
if needed!

DB-4062: Block editor button styles

---

.github/workflows/release-and-split.yml

Ignore the release scripts to finish the sprint release. Still not sure what is up with them at the moment but will dig in.
For now this should let us publish our sprint 32 release
if needed!

Ignore broken release scritps

---

.changeset/pre.json
.github/pull_request_template.md

- Enter prerelease mode
- Fix formatting for the PR template (the last line was being formatted in a weird way by prettier)
if needed!

Enter pre mode

---

.changeset/lovely-coins-fly.md
packages/drupal-kit/package.json
packages/nextjs-kit/package.json
packages/wordpress-kit/package.json

Update the types file in `drupal-kit` and `wordpress-kit` and ensure that TSDoc comments and other nice LSP features are working when our libraries our imported.
Locally with `npm link`, and some hacky editing of the `package.json` with the current release, but this should be tested again with a fresh canary release.

DB-4070, DB-4071: Fix types for umd bundle

---

tsconfig.json

Ideally we could hook into the `docusaurus build` script and only run the typedoc plugin to generate the API reference in CI. This does not seem to be possible, so hopefully this will fix the error in the action.
To the root tsconfig.

DB-4081: Try removing force casing in filenames

---

pnpm-lock.yaml
web/package.json

Removed workspace based dev dependencies for deployment :)
/web

DB-4018: remove workspace based dev dependencies for deployment

---

.changeset/late-dryers-collect.md
starters/next-wordpress-starter/lib/Pages.js
starters/next-wordpress-starter/lib/Posts.js
starters/next-wordpress-starter/pages/examples/ssg-isr.jsx
starters/next-wordpress-starter/pages/index.jsx
starters/next-wordpress-starter/pages/pages/index.jsx
starters/next-wordpress-starter/pages/posts/index.jsx

Updates maximum number of posts/pages returned.
`next-wordpress-starter`
Ran starter locally and observes all posts and pages are returned.
WP and graph ql default to displaying 10 results per query when an amount is not specified. There is no good way to return 'all data' other than assigning the `first` query param a value. I adjusted our page and post queries to accept a variable specifying the number of items to be returned. This should get us the desired functionality we want and also allow us to reuse queries a bit more. For example with this set up the home page showing only 12 results can use the same query of the posts list which has all posts. 

DB-3186: Update query parameters

---

.changeset/late-pens-arrive.md

Added missing changesets related to next-wordpress pager to ensure that they will be released. Specifically ensuring that all changes from https://github.com/pantheon-systems/decoupled-kit-js/pull/320/files are covered.

Add missing changesets for sprint 33 release

---

.github/templates/trigger-e2e.yml.template
.github/workflows/canary-sites-split.yml

Attempting to copy the necessary github action to add to the starter repo before the canary split. Won't be 100% positive that this will work until we try running it.
The hacky-er alternative is to instead create a new workflow in decoupled-kit-js that depends on canary-sites-split, and sleeps for 10 min before triggering the Circle CI sdk-test job in qa-automation. Gross, but I think it would work.
Somewhere in between those would be to git commit the workflow during CI. My hope is that this PR has the same end result.
They haven't been. Couldn't think of a practical way to test this locally.

DB-3768: attempt to add the trigger-e2e workflow prior to canary split

---

.github/workflows/canary-sites-split.yml

Added the github workspace path to attempt to correct file/directory related commands.

DB-3768: prefix github workspace to path

---

.github/workflows/canary-sites-split.yml

The mkdir command was failing because it was a nested directory. Added the -p flag to fix this.

DB-3768: ensure parent directory is created

---

.changeset/pre.json

Sprint 34 - exit prerelease mode

---

.changeset/happy-eggs-breathe.md
starters/gatsby-wordpress-starter/src/pages/404.jsx

The `gatsby-wordpress-starter` 404 page is styled to look similarly to the 404 page in the `next-wordpress-starter`
`gatsby-wordpress-starter`
The `gatsby-wordpress-starter` was ran locally and the 404 page was observed to be visually the same as the `next-wordpress-starter`.

DB-4562: Gatsby 404 page styles

---

.changeset/ninety-roses-jog.md
packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Spacer.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts

- Added Spacer component
`wordpress-kit`
Tested this component locally through a post in the `next-wordpress-starter` that used the spacer style. Observed expected styles and behavior.

DB-4066: Block spacer styles

---

.changeset/olive-jeans-begin.md
.changeset/ten-lemons-brake.md
starters/next-drupal-starter/README.md
starters/next-drupal-starter/next.config.js
web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-environment-variables.md

`` 
- The `FRONTEND_URL` is automatically set to `PANTHEON_ENVIRONMENT_URL` if defined.
- Docs updated to reflect this change
I deployed a site without setting the `FRONTEND_URL` env var and observed that the `hrefLang` was set correctly based off of the `PANTHEON_ENVIRONMENT_URL`.

DB-3747: Automatically set `FRONTEND_URL`

---

.changeset/four-wolves-chew.md
packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/contentWithImage.test.tsx.snap
packages/nextjs-kit/src/components/contentWithImage.tsx
starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap
starters/next-drupal-starter/__tests__/__snapshots__/default/articles.test.jsx.snap
starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap
starters/next-drupal-starter/__tests__/__snapshots__/umami/articles.test.jsx.snap
starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pages.test.jsx.snap
starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/posts.test.jsx.snap

- Refactor content with image component to have a default styling for the CMS content
- Wrapped the header in a section to apply width logic
- Nextjs-Kit
Locally, tested on Drupal and WordPress flavors, against the Canary site

DB-4060: Block Editor Alignment Options

---

.changeset/hungry-roses-destroy.md
packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Separator.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts

- Added Separator component
`wordpress-kit`
Tested this component locally through a post in the `next-wordpress-starter` that used the separator block. Observed expected styles and behavior.

DB-4065: Block separator styles

---

.changeset/wicked-dogs-report.md
packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Columns.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts

- Added columns layout component to the Tailwind plugin
- Locally

DB-4063: Block editor column styles

---

.changeset/healthy-seas-hide.md
.changeset/smooth-apes-rescue.md
packages/drupal-kit/package.json
packages/drupal-kit/src/lib/PantheonDrupalState.ts
pnpm-lock.yaml
starters/next-drupal-starter/__tests__/getPaths.test.js
starters/next-drupal-starter/__tests__/getPreview.test.js
starters/next-drupal-starter/lib/getPaths.js
starters/next-drupal-starter/lib/getPreview.js
starters/next-drupal-starter/lib/stores.js
starters/next-drupal-starter/pages/[...alias].jsx
starters/next-drupal-starter/pages/api/preview.js
starters/next-drupal-starter/pages/articles/[...slug].jsx
starters/next-drupal-starter/pages/articles/index.jsx
starters/next-drupal-starter/pages/examples/auth-api.jsx
starters/next-drupal-starter/pages/examples/index.jsx
starters/next-drupal-starter/pages/examples/pagination/[[...page]].jsx
starters/next-drupal-starter/pages/examples/ssg-isr.jsx
starters/next-drupal-starter/pages/index.jsx
starters/next-drupal-starter/pages/pages/[...alias].jsx
starters/next-drupal-starter/pages/pages/index.jsx
starters/next-drupal-starter/pages/recipes/[...slug].jsx
starters/next-drupal-starter/pages/recipes/index.jsx
web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md

In the `next-drupal-starter`, instances of DrupalState no longer require separate instances for auth’d and non-auth’d stores.
`drupal-kit`
Starter was ran locally and observed to be functioning properly using a single store for auth'd and anonymous responses.  

DB-3674: Refactor Stores

---

.changeset/breezy-mangos-smell.md
starters/gatsby-wordpress-starter/gatsby-config.js
starters/gatsby-wordpress-starter/lib/privatePosts.js

- In the gatsby-config.js, ensure the PANTHEON_CMS_ENDPOINT env var has the proper protocol so that it is not set multiple times, as the config file is rerun during build
- in privatePosts, pass in a valid endpoint
gatsby-wp-starter
tested locally with either WPGRAPHQL_URL or PANTHEON_CMS_ENDPOINT env vars set.

[gatsby-wordpress] Fix URL for graphql client if WPGRAPHQL_URL is not set

---

packages/drupal-kit/package.json
packages/wordpress-kit/package.json

Remove workspace from cms-kit version in drupal-kit and wordpress-kit

fix: remove workspace from cms-kit version

---

.changeset/big-zebras-speak.md
packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Image.ts

- Instead of setting a width: 100%, use max-width to follow WP spirit

DB-4829: Images Can Scale Past Native Width and Height

---

package.json
pnpm-lock.yaml
web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
web/docusaurus.config.js
web/package.json

- Fix prettier config path in web
- Prettier format on package.json changed spaces -> tabs
- Fixed the prettier config in the root package.json as well
- Add docs for surrogate key based cache purging for Drupal and WP
- Upgrade docusaurus 2.2.0
- Add docusaurus mermaid plugin which adds support for mermaid diagrams

DB-3832: Document surrogate key based cache purging

---

.changeset/slow-apples-hunt.md
.github/workflows/canary-release.yml
.github/workflows/release-and-split.yml
package.json
pnpm-lock.yaml
starters/gatsby-wordpress-starter/package.json

Hopefully this will fix or give more insight into why the action is failing. A bug was found with gatsby dev mode with `pnpm@7.17.1` and this should alleviate that.
- add eslint@^7.5.0 to gatsby-wp-starter
- include the eslint-config workspace in the root package.json
This should close #427 but I'm still a bit lost on why the Action is failing.

Fix gatsby dev mode, use pnpm cache in github action

---

web/docs/Frontend Starters/Next.js/Next.js + WordPress/implementing-preview.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-cache-control-header.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/styling-configuration.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/your-first-customization.md

Added a new doc under the next+wp section about implementing preview
Also changed the sidebar positions to match the next+drupal section 

DB-4953: [docs] Add implementing-preview to next+wp docs

---

.changeset/angry-rules-knock.md
.changeset/eight-waves-behave.md
.changeset/large-donuts-mix.md
packages/cms-kit/src/utils/setSurrogateKeyHeader.ts
packages/drupal-kit/src/lib/defaultFetch.ts
packages/wordpress-kit/__mocks__/server/basicPostsQuery.ts
packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts
web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md

- Instead of setting `Pantheon-Debug`, `wordpress-kit` and `drupal-kit` fetch methods now set `Pantheon-SKey`
- Instead of setting `Surrogate-Key-Raw` on outgoing responses, `cms-kit`'s `setSurrogateKeyHeader` now sets the `Surrogate-Key` header on the outgoing response.
- The appropriate docs  have been updated as needed
cms-kit, drupal-kit, wordpress-kit, docs
Tests pass
tested locally with each starter kit against our default QA backends to ensure correct header is output in the browser.

DB-883: Update surrogate key headers

---

.changeset/poor-ducks-decide.md
starters/next-drupal-starter/lib/getPreview.js
starters/next-drupal-starter/pages/api/preview.js

Drafts are not currently supported for Drupal's decoupled_preview. This change adds a clearer error message in the case a user tries to preview a draft.
locally

DB-4935: Error if previewing a draft

---

.changeset/eighty-timers-fold.md
packages/wordpress-kit/__tests__/GraphqlClientFactory.test.ts
packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts

- Support GraphQL over HTTP GET added to the `wordpress-kit`
- `wordpress-kit`
- A GraphQL client was created to support GET requests and the use of this client resulted in successful cache hits.
-   

DB-5231: Support GraphQL over HTTP GET

---

.changeset/happy-moose-try.md
packages/create-pantheon-decoupled-kit/package.json
pnpm-lock.yaml

fix fs-extra mistakenly marked as dev dependency

Fix missing dependency

---

pnpm-lock.yaml
starters/gatsby-wordpress-starter/package.json

Upgrade `gatsby-source-wordpress` to latest version compatibale with Gatsby 4
Site builds locally against the newly updated backend

Upgrade `gatsby-source-wordpress`

---

CONTRIBUTING.md
packages/create-pantheon-decoupled-kit/README.md
packages/create-pantheon-decoupled-kit/index.ts
packages/create-pantheon-decoupled-kit/package.json
packages/create-pantheon-decoupled-kit/src/utils/index.ts
packages/create-pantheon-decoupled-kit/watch.example.ts
web/docs/Packages/create-pantheon-decoupled-kit/index.md
web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DecoupledKitGenerator.md
web/docs/Packages/create-pantheon-decoupled-kit/interfaces/_category_.yml
web/docs/Packages/create-pantheon-decoupled-kit/modules.md
web/docusaurus.config.js

Add docs for contributing to/developing with the cli.
- `CONTRIBUTING.md`, 
- `create-pantheon` - created barrel files for utils and all exports so that typedoc picks up everything
I tacked the docs onto CONTRIBUTING.md, but open to putting them somewhere else. I wasn't sure if we should make a new entry somewhere in `/docs/Frontend Starters`. If we want it in `/docs/Packages/create-pantheon-decoupled-kit` after the API ref is generated, we might need to write some custom script. There didn't seem to be a way to include arbitrary markdown files in the `typedoc` output, or at least the one feature that did was about to be deprecated (couldn't get it working anyway :))

DB-5059: Add docs for developing with the cli

---

.circleci/config.yml
README.md
package.json
pnpm-lock.yaml
web/docs/contributing.md

- Upgrade pnpm to `7.26.3` in all relevant docs and configs including CI
build, test and ran all packages and starters
Some relevant  issues here:
https://github.com/pnpm/pnpm/issues/5621
https://github.com/pnpm/pnpm/pull/5829

Upgrade pnpm to fix `pnpm config` in CI

---

.changeset/hip-seas-beam.md
.changeset/tasty-roses-jog.md
packages/drupal-kit/src/__tests__/PantheonDrupalState.test.ts
packages/drupal-kit/src/lib/defaultFetch.ts
packages/wordpress-kit/__tests__/setEdgeHeader.test.ts
packages/wordpress-kit/src/lib/setEdgeHeader.ts
web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-cache-control-header.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-cache-control-header.md
web/docs/Packages/drupal-kit/modules.md

- Server side rendered responses now use a Cache-Control header of public, s-maxage=600
- Documentation updated accordingly.
`drupal-kit`
`wordpress-kit`
./web
Starter observed to run normally with updated headers.

DB-5376: Update Default Cache Control Values

---

web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md

Minor updates and cross linking between WP Caching Considerations and WP Next Surrogate Key Based Purging.
Docs.
Ran the docs site locally.

DB-5240: loose ends for GraphQL Caching Docs

---

.github/workflows/canary-release.yml
.github/workflows/canary-sites-split.yml
.github/workflows/release-and-split.yml
README.md
web/docs/contributing.md

- Use the CLI in CI to generate starters before split action
- Fixed outdated pnpm version on some docs
- Fixed? the github action output for the slack message; it should now give us slightly more info
GitHub Actions split jobs
PoC on personal GitHub account
Honestly did not think it would work. (famous last words)

DB-5253: Use CLI to generate starters for mirrors

---

web/docs/Backend Starters/Decoupled WordPress/add-ons.md
web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md
web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/add-ons.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/add-ons.md

A new entry titled ‘Add-ons’ is added to the Decoupled Kit developer docs under Backend Starters → Decoupled WordPress.
In the documentation part of  Backend Starters → Decoupled WordPress.

DB-5402: Add-on docs for Advanced Custom Fields.

---

.github/workflows/canary-sites-split.yml
.github/workflows/release-and-split.yml

A few things are not working with the latest CI changes:
1. the docs workspace did not get published.
2. some repo names were not correct in the split workflows
3. build failed for the two repos that were _correct_
1 and 2 should hopefully be solved by the changes below. I am still a bit stumped as to why the builds failed for the 2 splits that were correct.
My guess is that these repos have the `.env.development.local` file inside the repo, even though they should be gitignored, which is causing the builds to fail because that file is basically empty. 
Another interesting development is that [the `.gitignore` file which I would expect to be committed to the split repo, instead was renamed to `.npmignore`](https://github.com/pantheon-systems/next-drupal-starter-umami-canary/commit/bcfe187b …

DB-5253: Fix workflow files output repo

---

.changeset/red-kings-help.md
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/gatsby-config.js.hbs

Our canary build for the gatsby-wp starter failed due to this plugin missing in the package.json (expected), but still defined in the `gatsby-config.js`. This change will ensure a starter generated wtihout pnpm does not load this plugin in `gatsby-config.js`
CLI package > gatsby-wp templates

Add conditional for gatsby-plugin-pnpm in gastby-config

---

.changeset/mean-buckets-perform.md
packages/create-pantheon-decoupled-kit/__tests__/actionRunner.test.ts
packages/create-pantheon-decoupled-kit/package.json
packages/create-pantheon-decoupled-kit/scripts/watchTemplates.ts
packages/create-pantheon-decoupled-kit/src/actions/addWithDiff.ts
packages/create-pantheon-decoupled-kit/src/index.ts
packages/create-pantheon-decoupled-kit/src/utils/actionRunner.ts
packages/create-pantheon-decoupled-kit/src/utils/dedupeTemplates.ts
packages/create-pantheon-decoupled-kit/watch.example.ts
pnpm-lock.yaml

- Use tsx instead of vite-node
- Use tsx watch mode to watch for changes to watch.ts. Useful for changing variables on the fly while running a generated starter.
- Fix lint issues, remove lint ignore tag
- Clean up listeners on exit to avoid memory leaks
- Export rootDir from index to fix running main() with tsx
cli watchScript and minor changes to the way rootDir is handled across the app. It is now imported from `index.ts` so that running the app without a build step like with `tsx` works properly.

DB-5385: Watch script refinements

---

.changeset/wise-impalas-yawn.md
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.npmignore
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/.npmignore
packages/create-pantheon-decoupled-kit/src/templates/next-wp/.npmignore

Remove .npmignore from the templates. They shouldn't be needed anymore.
Must have missed this with the previous ticket to change the .gitignore strategy.
cli > project templates

Remove .npmignores from project templates

---

package.json
scripts/ci-version

This should ensure the `create-pdk`'s `bin.js` includes the very latest versions when we publish. Without the build, I think our published versions will be one behind, but this should fix it.
@backlineint Would making this build a `prepublish` step make more sense?

DB-5636: Ensure latest versions are published

---

.changeset/proud-eels-dress.md
packages/create-pantheon-decoupled-kit/__tests__/actionRunner.test.ts
packages/create-pantheon-decoupled-kit/__tests__/addDependencies.test.ts
packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
packages/create-pantheon-decoupled-kit/src/actions/addDependencies.ts
packages/create-pantheon-decoupled-kit/src/actions/index.ts
packages/create-pantheon-decoupled-kit/src/actions/runInstall.ts
packages/create-pantheon-decoupled-kit/src/generators/index.ts
packages/create-pantheon-decoupled-kit/src/generators/tailwindcss-addon.generator.ts
packages/create-pantheon-decoupled-kit/src/index.ts
packages/create-pantheon-decoupled-kit/src/templates/tailwindcss-addon/postcss.config.cjs
packages/create-pantheon-decoupled-kit/src/templates/tailwindcss-addon/styles/globals.css
packages/create-pantheon-decoupled-kit/src/templates/tailwindcss-addon/tailwind.config.cjs
packages/create-pantheon-decoupled-kit/src/types.ts
web/docs/Frontend Starters/create-pantheon-decoupled-kit.md

- Added a new action, `addDependencies`, that will add any dependencies listed in a generators `data` field to the `package.json` found in the `outDir`.
- Added a new generator `tailwindcss-addon` that uses the `addDependencies` action, as well as the `addWithDiff` action to bootstrap a project with tailwindcss dependencies and configs
- Added a `nextSteps` option to generators, so that any crucial information relating specifically to the generator can be logged to the console when all actions are complete.
- Added tests for the `addDependencies` action
-Some tweaks to the `Input` type
- Added this add-on to the CLI docs.
cli, docs
wrote tests, and used the generator on a React project created with `npm init vite`. After minimal changes (importing the proper css file and removing styles …

DB-5055: tailwindcss addon

---

.changeset/long-yaks-lie.md
packages/create-pantheon-decoupled-kit/src/generators/index.ts
packages/create-pantheon-decoupled-kit/src/generators/next-drupal-search-api-addon.generator.ts
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/[...alias].test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/articles.test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/auth-api.test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/examples-index.test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/homepage.test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/pages.test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/pagination.test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/ssr-isr-example.test.jsx.snap
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/snapshotTests/auth-api.test.jsx
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/snapshotTests/homepage.test.jsx
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/layout.jsx
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/search-input.jsx

- Creates a new addon, `next-drupal-search-api-addon`, which has the start of an example implementation for the Drupal Search API
- A search box is included in the header in all existing next-drupal starter kit routes.
- Submitting a search redirects to `/search/<term>`
`cli`
Generated a new project using the locally linked `create-pantheon-decoupled-kit` package. The `next-drupal` and `next-drupal-search-api-addon` generators were used along side each other with no problems. A new project was generated with the new search functionality working as expected.
Testing considerations:
I experimented with one off unit tests for this component but since our `/search`  page has not been implemented and an essential duplicate of this component will be built for use in the `app` directory, I …

DB-5712: Add CSR Search Input to `/pages` Layout

---

.github/workflows/canary-sites-split.yml
.github/workflows/release-and-split.yml

The `--tailwindcss` flag is now required for CI to not hang. Maybe theere is an oppurtunity for `CI` mode on the CLI that will select the default answer if it is not passed in via flag and CI mode is true.
canary-sites-split.yml & release-and-split.yml

Add tailwindcss flag to next-wp generator_commands

---

.changeset/chilled-icons-obey.md
packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
packages/create-pantheon-decoupled-kit/src/templates/partials/tailwindcssDeps.hbs

`tailwindcss` is a required dependency for our `wordpress-kit` because of the plugin. This means that the output of a tailwindless next-wp project will fail without this dependency. If `auto-install-peers` is set to true, depending on the package manager, this isn't an issue. But we should not rely on users needing to install this dependency themselves.
Adds `tailwindcss` back to the `next-wp` package.json in all cases
Tested locally with the watch script

DB-5227: Fix missing dependency

---

.changeset/pre.json
packages/cms-kit/CHANGELOG.md
packages/cms-kit/package.json
packages/create-pantheon-decoupled-kit/CHANGELOG.md
packages/create-pantheon-decoupled-kit/package.json
packages/drupal-kit/CHANGELOG.md
packages/drupal-kit/package.json
packages/nextjs-kit/CHANGELOG.md
packages/nextjs-kit/package.json
packages/wordpress-kit/CHANGELOG.md
packages/wordpress-kit/package.json

Revert latest canary release which failed

Revert "Canary Release (canary)"

---

.github/workflows/canary-release.yml
.github/workflows/canary-sites-split.yml
.github/workflows/release-and-split.yml
.npmrc

- Add registry string to `.npmrc`
- Remove write of `.npmrc` from the Actions workflows
- Add `NPM_TOKEN` to action `env` to be read by the `.npmrc` during the action
`.npmrc` and GitHub actions workflows
If the `.npmrc` is completely missing from the repo, it will be created by the changeset "Canary version" action. This commits that file back to the repo with our secret exposed. This is a problem! I have just tested another canary release with a blank `.npmrc` which seems to prevent the exposed secret issue, however it does not seem to work for the actual publish.
This change should make sure that
1. the `npmrc` is already in the repo so it should not need to be created during the changeset action
2. the token is not written at all during CI, it is instead read from a secret env var. …

Move .npmrc write out of actions

---

.github/workflows/canary-sites-split.yml
.npmrc

Putting the `${NPM_TOKEN}` env var in the `.npmrc` causes a bunch of noisy warnings when doing anything with `pnpm` locally if this var is not set.
CI should work with a blank `.npmrc` as long as `NPM_TOKEN` is defined in the `env`.
This PR should fix those warnings from a missing `NPM_TOKEN`, as well as fix the CI jobs.
`NPM_TOKEN` is removed from canary-sites-split since that action does not need it.
CI

Use empty .npmrc, update NPM_TOKEN in CI workflows

---

web/docs/Backend Starters/Decoupled WordPress/configuring-build-hooks.md

Updated WordPress build hooks entry to prevent duplicate hook submissions
Docs -> BE -> WP -> Configuring Build Hooks.

DB-5804: update WordPress build hooks entry to prevent duplicate hook submissions

---

.changeset/funny-owls-build.md
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.jsx

- Formatting tweaks applied to the `gatsby-wp-acf-addon` to satisfy linter on instillation.
`cli > templates > gatsby-wp-acf-addon`
New projects with the gatsby-wp-acf-addon installed pass lint locally.

DB-5693: Adjust Add-on Formatting to Satisfy Lint

---

.github/workflows/release-and-split.yml

The `generate_cmd` for the next-drupal-starter in `release-and-split.yml` now needs the --tailwindcss flag
ci

Add --tailwindcss flag to next-drupal-starter release split cmd

---

.changeset/fluffy-suits-knock.md
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.jsx
packages/create-pantheon-decoupled-kit/src/templates/partials/next-wp/nextWpPostView.hbs
packages/create-pantheon-decoupled-kit/src/templates/partials/next-wp/nextWpPostsJS.hbs

- Small query adjustments and layout adjustments to the ACF add-ons to work with a new WordPress for Front-End project.
`cli > templates > next-wp-acf-addon && gatsby-wp-acf-addon`
Both ACF starters were generated without warnings and were able to successfully query a WP backend with ACF enabled.

DB-5693: Starter Kit ACF Adjustments

---

.github/workflows/canary-sites-split.yml
.github/workflows/release-and-split.yml

Set an empty `--cmsEndpoint` so that CI does not break
release workflows

Omit cmsEndpoint in generator_cmd

---

packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md
packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md
web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/intro.md
web/docs/Frontend Starters/Next.js/Next.js + Drupal/intro.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/intro.md
web/docs/Frontend Starters/create-pantheon-decoupled-kit.md
web/docs/Packages/cms-kit/modules.md
web/docs/Packages/create-pantheon-decoupled-kit/index.md
web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DecoupledKitGenerator.md
web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DefaultAnswers.md
web/docs/Packages/create-pantheon-decoupled-kit/interfaces/TemplateData.md
web/docs/Packages/create-pantheon-decoupled-kit/modules.md
web/docs/Packages/drupal-kit/classes/DrupalState.md
web/docs/Packages/drupal-kit/interfaces/authInit.md
web/docs/Packages/drupal-kit/modules.md
web/docs/Packages/nextjs-kit/interfaces/ContentProps.md
web/docs/Packages/nextjs-kit/interfaces/FooterMenuProps.md
web/docs/Packages/nextjs-kit/interfaces/HeaderProps.md
web/docs/Packages/nextjs-kit/interfaces/LinkProps.md
web/docs/Packages/nextjs-kit/interfaces/PaginationProps.md
web/docs/Packages/nextjs-kit/interfaces/PreviewRibbonProps.md
web/docs/Packages/nextjs-kit/interfaces/RecipeProps.md
web/docs/Packages/nextjs-kit/interfaces/SortOptions.md
web/docs/Packages/nextjs-kit/modules.md

- Docs with `npm init` commands that use args have been updated to include the double dash that is required to forward args to the command
- Generated api reference - I meant to do this last sprint and we're a bit behind. Seems like an OK time to do this.
`web/docs`, project generator READMEs

[docs] Docs update npm init

---

.changeset/olive-wolves-call.md
.changeset/weak-dragons-agree.md
packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts
web/docs/Packages/wordpress-kit/classes/GraphqlClientFactory.md

- Use proper type from graphql-request in GraphQLClient factory in wp-kit
- Generate new api ref for this class
- Add changesets. Bump included for create- so that the canary version includes the latest wp-kit version.
`wordpress-kit`. API ref docs were also regenerated.
Tests pass, no more TS errors

DB-5914: Fix GraphQLFactory options type

---

.changeset/clever-ties-smile.md
.changeset/light-socks-protect.md
.changeset/perfect-dolphins-relax.md
.husky/pre-commit
packages/cms-kit/src/utils/setSurrogateKeyHeader.ts
packages/drupal-kit/src/lib/PantheonDrupalState.ts
scripts/generate-starters.ts

- `cms-kit`: TypeScript was yelling about this Set being iterated over. I'm not sure how this is different but it no longer complains.
- `drupal-kit`: Override the getObject methods to take in a generic and return data of that type.
- monorepo: A few QoL updates for the monorepo. no longer run tests or lint in the `starters` workspace on commit hook since we don't really care if those are broken now. Also, add `cmsEndpoint` to the generate-starters script.
`cms-kit`, `drupal-kit`, scripts, and pre-commit hook.
tests pass, no TS errors when using these methods in the starters

DB-5574: getObject generic

---

.changeset/cyan-colts-lay.md
.changeset/smooth-bees-pretend.md
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.hbs
packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDeps.hbs
packages/wordpress-kit/package.json
pnpm-lock.yaml

- Tailwind in no longer a peer dependency in `wordpress-kit`.
- Tailwindless starters that use `wordpress-kit` no longer install tailwind as a dependency.
`cli` `wordpress-kit`
All starter were generated locally both with and without tailwind and worked as expected.

DB-5908: Include Proper Tailwindcss Deps in `wordpress-kit`

---

.changeset/blue-needles-sit.md
.changeset/mean-falcons-destroy.md
.changeset/small-feet-camp.md
packages/cms-kit/__tests__/setSurrogateKeyHeader.test.ts
packages/cms-kit/src/utils/setSurrogateKeyHeader.ts
packages/cms-kit/vite.config.js
packages/drupal-kit/src/lib/defaultFetch.ts

- update `setSurrogateKeyHeader` to remove the first two keys if there are more than 2. I'm not positive this logic is correct for all cases and it's hard to debug the hashed values because they are hashed. I was going off of the assumption that the test input wouldn't change, but maybe the `resourceKeys` in the `cms-kit` test is no longer valid?
- Update `defaultFetch` to get and set the `Surrogate-Key` header instead of `Surrogate-Key-Raw`
Tested locally with a generated starter inside the monorepo.
Fastly sets `Surrogate-Key` not `Surrogate-Key-Raw`. I could see the desire to do the hashing ourselves if debugging becomes an issue.

DB-6013: Update `setSurrogateKeyHeader` and `drupal-kit` `defaultFetch`

---

.changeset/curly-spoons-yell.md
.changeset/silly-pots-arrive.md
.prettierignore
packages/cms-kit/__tests__/setSurrogateKeyHeader.test.ts
packages/create-pantheon-decoupled-kit/src/templates/next-wp/lib/setOutgoingHeaders.js
packages/wordpress-kit/__mocks__/server/basicPostsQuery.ts
packages/wordpress-kit/__tests__/GraphqlClientFactory.test.ts
packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts
web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md

**Merge after #665**
- Update `wordpress-kit` GraphQLClientFactory to add `Fastly-Debug` header instead of `Pantheon-SKey`
- Update docs relating to `Surrogate-Key-Raw`, change to `Surrogate-Key`
`wordpress-kit`, `cli` templates, `docs`
Locally with generated starter in monorepo

DB-6014: `wordpress-kit` hashed surrogate keys

---

.changeset/twelve-hats-grin.md
packages/create-pantheon-decoupled-kit/package.json
pnpm-lock.yaml

Add some `devDependencies` to `dependencies`.
`cli`
Canary split action failed due to missing dependencies. This should fix it.

Move required deps to dependencies from devDeps

---

.changeset/thick-hotels-check.md
.changeset/tidy-rocks-brake.md
packages/wordpress-kit/package.json
packages/wordpress-kit/src/tailwindcssPlugin/index.ts
packages/wordpress-kit/vite.config.js

"You got your drupal-kit in my wordpress-kit!"
Fix some typos
add the `.js` extension to the tailwind/plugin import – this is what actually broke the build of the canary site.
`wordpress-kit`

Fix wordpress-kit exports

---

.changeset/ninety-cooks-melt.md
packages/create-pantheon-decoupled-kit/src/templates/next-wp/styles/globals.css.hbs
packages/create-pantheon-decoupled-kit/src/templates/partials/nextjs-shared/nextjsGridCSS.hbs
packages/create-pantheon-decoupled-kit/src/templates/partials/nextjs-shared/nextjsLayoutCSS.hbs

Add styles + global css explicitly to `next-wp` templates and fixed some colors

Fix missing next-wp styles

---

.changeset/strange-shrimps-learn.md
packages/create-pantheon-decoupled-kit/.eslintrc
packages/create-pantheon-decoupled-kit/src/actions/convertCSSModules.ts
packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp-acf-addon.generator.ts
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.jsx
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.module.css.hbs
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/page.module.css.hbs
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/post.module.css.hbs

- Specify eslint ignore files in cli .eslintrc
- Add css modules for gatsby-wp-acf-addon
- Make page & post widths consistent
`cli`, `gatsby-wp-acf-addon` templates
Locally w/watch script
Added the `.jsx` files to the ignorePatterns in `.eslintrc` of the cli to avoid errors on those files. They are still able to be formatted by prettier. The gatsby acf addon however doesn't have the gatsby `.prettierrc` so if you format it it will add semicolons etc. In case you need to format that one file you can temporarly add the `.prettierrc` to the addon dir.

DB-6039: [gatsby-wp-acf-addon] Use css modules by default

---

.changeset/four-foxes-check.md
configs/eslint/CHANGELOG.md
configs/eslint/package.json
packages/cms-kit/package.json
packages/configs/eslint/package.json
packages/configs/other/package.json
packages/create-pantheon-decoupled-kit/package.json
packages/drupal-kit/package.json
packages/nextjs-kit/package.json
packages/wordpress-kit/package.json

A changeset for the wrong config package was released. This should revert the behavior and apply the changeset to the appropriate package. Nothing was accidentally published because the private field is set in the package.json
- Fix changeset
- Revert changes made by the canary release to our workspace config

Revert canary release of eslint-config, add changeset for proper package

---

.changeset/mighty-bears-wave.md
.github/workflows/canary-sites-split.yml
.github/workflows/release-and-split.yml
packages/create-pantheon-decoupled-kit/src/generators/next-drupal-umami-addon.generator.ts
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-umami-addon/components/grid.module.css.hbs
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-umami-addon/components/recipeGridItem.jsx
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/components/grid.jsx
packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/nextDrupalCatchAllView.hbs
packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/sharedNextDrupalConfig.hbs
packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/catch-all.module.css.hbs

- Use css modules by default for the Umami addon
- add convertCSS action to umami addon
next-drupal-umami-addon templates
Locally w/watch script

DB-6041: Use css-modules for the umami addon

---

.changeset/famous-bugs-drum.md
packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/pagination/[[...page]].jsx

- Add imports that were removed from the pagination example in the `next-wp-starter`
next-wp template
- Tested locally and observed import errors go away.

DB-6038: Update Imports in Pagination Page

---

.changeset/funny-eggs-sip.md
.changeset/mighty-numbers-fail.md
packages/create-pantheon-decoupled-kit/src/templates/next-wp/next.config.js
packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/sharedNextDrupalConfig.hbs
packages/nextjs-kit/__tests__/snapshotTests/__snapshots__/contentWithImage.test.tsx.snap
packages/nextjs-kit/__tests__/snapshotTests/__snapshots__/recipe.test.tsx.snap
packages/nextjs-kit/package.json
packages/nextjs-kit/src/components/contentWithImage.tsx
packages/nextjs-kit/src/components/paginator.tsx
packages/nextjs-kit/src/components/recipe.tsx
packages/nextjs-kit/vite.config.js
pnpm-lock.yaml

- Use `next/compat/router` (https://github.com/vercel/next.js/issues/43585#issuecomment-1379966686)
- Add `nextjs-kit` to `next.config.transpilePackages` for all next generators
This seems to resolve the `NextRouter was not mounted` error, at least locally
Tested locally with the watch script and a fresh `create-next-app` app symlinked to the `nextjs-kit`

Use `next/compat/router`

---

.changeset/violet-donuts-lay.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/api/preview.js

Decode the `req.url` before testing against the default locale. This is now required because the url comes back encoded from Cloudflare.
`next-drupal` templates
Tested with the `05-18-23-preview` site in the QA workspace
Unclear what needs to happen on the WP side at this time.

Decode req.url before regext.test in `preview` api route

---

.changeset/clean-toes-speak.md
.changeset/funny-rules-rule.md
.changeset/odd-items-arrive.md
package.json
packages/nextjs-kit/__tests__/snapshotTests/__snapshots__/contentWithImage.test.tsx.snap
packages/nextjs-kit/__tests__/snapshotTests/__snapshots__/recipe.test.tsx.snap
packages/nextjs-kit/package.json
packages/nextjs-kit/src/components/contentWithImage.tsx
packages/nextjs-kit/src/components/paginator.tsx
packages/nextjs-kit/tsup.config.ts
packages/nextjs-kit/vite.config.js
packages/wordpress-kit/package.json
pnpm-lock.yaml

Use tsup for the nextjs-kit bundle as vite (or rollup) was including some external code that was breaking in the browser. tsup seems to have the correct bundle that works with Next.js now (previously it did not).
Previously when re-doing the nextjs kit bundle, I tried tsup but it would not work properly when importing into a nextjs application. I believe this was due to a bug in next which seems to have been fixed. At the same time, with next `>=13.4`, the vite bundle was not excluding some dependency properly which led to the inclusion of `__dirname` in the bundle which was breaking in the browser.
This seems to have fixed that bug. Now there is another bug where react hooks like `useState` are missing in the browser. This is being investigated by the Next.js team, but they still need a …

Fix nextjs-kit compatibility with Next.js 13.4

---

web/docusaurus.config.js

changed `decoupled-drupal` -> `decoupled-wordpress`
docs

[docs ] Fix incorrect link in docs footer

---

.changeset/seven-moose-sit.md
packages/create-pantheon-decoupled-kit/src/templates/next-wp/.prettierrc

The `next-wp` did not have a `.prettierrc` so the `prettier:fix` command failed in CI. This should solve it.
`next-wp` template
locally create and successfully formatted the output.

Add .prettierrc to next-wp template

---

.changeset/mighty-impalas-appear.md
.changeset/rich-cows-arrive.md
packages/nextjs-kit/package.json
packages/nextjs-kit/src/components/grid.tsx
pnpm-lock.yaml

`nextjs-kit` was failing to build locally. After adding `@types/react` and `@types/react-dom` to the package `devDependencies`, it seems to be building successfully. Also adjusted a few of the types.
built package locally and tested locally with `generate-starters` 

Add @types/react & @types/react-dom to nextjs-kit devDeps

---

.changeset/tiny-bugs-live.md
packages/create-pantheon-decoupled-kit/__tests__/addWithDiff.test.ts
packages/create-pantheon-decoupled-kit/__tests__/fixtures/addWithDiff/populated/test-anotherFileWithDiff.js
packages/create-pantheon-decoupled-kit/__tests__/fixtures/addWithDiff/populated/test-ts-template.ts
packages/create-pantheon-decoupled-kit/__tests__/fixtures/addWithDiff/populated/test-withDiff.js
packages/create-pantheon-decoupled-kit/__tests__/taggedTemplateHelpers.test.ts
packages/create-pantheon-decoupled-kit/__tests__/templates/addWithDiff/test-can-be-empty.ts.ts
packages/create-pantheon-decoupled-kit/__tests__/templates/addWithDiff/test-ts-template.ts.ts
packages/create-pantheon-decoupled-kit/src/actions/addWithDiff.ts
packages/create-pantheon-decoupled-kit/src/types.ts
packages/create-pantheon-decoupled-kit/src/utils/index.ts
packages/create-pantheon-decoupled-kit/src/utils/taggedTemplateHelpers.ts

- Add support for tagged template literal templates
- Add helpers for the tagged template literal templates
- These are the same as the handlebars helpers, but the types are slightly different so I figured it was worth separating them. Especially since we will deprecate and remove the handlebars stuff eventually.
- Add tests for the new template format
`cli` `addWithDiff`
tests!
Part 1 of DB-5244 in effort of keeping PRs more reviewable.

DB-5244: Add tagged template support in addWithDiff + tests

---

.changeset/stupid-terms-travel.md
packages/drupal-kit/__mocks__/server/getDrupalSearchResultsResponseHandlers.ts
packages/drupal-kit/__tests__/getDrupalSearchResults.test.ts
packages/drupal-kit/src/lib/getDrupalSearchResults.ts

- `getDrupalSearchResults` now uses `example_index` as it's default index to fetch. 
- `drupal-kit`
A new Search API starter was generated through the cli and observed to successfully query the `example_index`.

DB-6288: `getDrupalSearchResults` uses `example_index`

---

.changeset/pretty-waves-float.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...searchAlias]].jsx

- Changed search result article links to point to the correct object.
`cli < templates < next-drupal-search-api-addon`
A new project was generated locally and seen to have working search result links.

DB-6289: Fix Broken Search Links

---

web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md

Added wordpress-kit code sample to surrogate key docs page.
docs.
Running docusaurus locally.

DB-4188: add wordpress-kit code sample to surrogate key docs page

---

.changeset/dirty-garlics-switch.md
packages/nextjs-kit/package.json
packages/nextjs-kit/tsup.config.ts

Porting over the changes to the `nextjs-kit` bundle in #738 over to canary so we can test locally a bit easier using the canary release.
Tested with the nextjs app directory

Fix subpath exports for nextjs-kit

---

.changeset/rotten-hotels-provide.md

added a changeset for the CLI
Ensure CLI is published on the next release so the templates receive the latest version of nextjs-kit

Add changeset to bump nextjs-kit version in the CLI

---

packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/getPosts.ts.ts

Forgot to wrap this query in the backticks util the first time. No changeset because this is going to get grouped in with the rest of the releases on this branch and it doesn't seem worthy of the changelog in the long term.

Fix gatsby wp `getPosts` template

---

web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md

Removed adjustment to next.config from the Drupal Next surrogate key example as it is no longer necessary.
Next Drupal Developer docs.
Ran docs locally.

Next config change no longer necessary for Drupal surrogate key example

---

web/docs/Backend Starters/terminus-decoupled-kit-plugin.md

Added documentation for terminus plugin. Placed at the root of backend navigation, similar to the CLI docs.
Docs
Running the docs site locally.

DB-5777: developer docs for terminus-decoupled-kit plugin

---

.changeset/blue-trainers-knock.md
.changeset/grumpy-lamps-act.md
packages/decoupled-kit-health-check/src/bin.ts

Forgot to account for the protocol missing on the `PANTHEON_CMS_ENDPOINT` when connecting a CMS via the dashboard. This should fix it.
healthcheck script
Locally

DB-6269: Fix missing https in `PANTHEON_CMS_ENDPOINT`

---

.changeset/cool-worms-drive.md
.changeset/plenty-pillows-drop.md
packages/decoupled-kit-health-check/src/next-wp.ts

- Make sure the endpoint ends with `/wp/graphql` when checking WordPress
dkhc
Tested changes locally

DB-6450: Ensure endpoint ends with `/wp/graphql`

---

.changeset/weak-papayas-cheat.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/api/preview.js

Add logic to the `next-drupal` starter's preview route so that the query param `test=true` returns JSON instead of the usual redirect to the page with the preview data.
`next-drupal` templates in the CLI
Tested locally by hand crafting the URL
When trying to hit the preview route with my hand crafted URL, I was not able to include the language as a segment of the path, which is what the route currently uses to get the locale. The locale is needed to use the correct DrupalState store. I ended up passing the locale in as another query param. This should be fine as it will be ignored if the lang is included on the path segment, but I wonder if there is a better way, or if we should embrace the query param and send it from the Drupal side as well.
Don't forget to [add a …

DB-4444: [next-drupal] preview route test option

---

.changeset/tender-mayflies-notice.md
.changeset/weak-papayas-cheat.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/api/preview.js
packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/api/preview.js

Add logic to the `next-wp` starter's preview route so that the query param test=true returns JSON instead of the usual redirect to the page with the preview data.
next-wp template
Locally

DB-6463: [next-wp] preview test option

---

.changeset/healthy-brooms-camp.md
packages/create-pantheon-decoupled-kit/esbuild.js
packages/create-pantheon-decoupled-kit/lint-staged.config.cjs
packages/create-pantheon-decoupled-kit/package.json
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.env.development.local.hbs
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.env.development.local.ts
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/gatsby-config.ts.ts
packages/create-pantheon-decoupled-kit/src/types.ts
packages/create-pantheon-decoupled-kit/src/utils/constants.ts

- Fix a typo in the gatsby config
- Use .ts template for .env.development.local
- Added `cmsEndpoint` to the Input type and made them non-optional
cli
gatsby-wp templates
locally

DB-6542: Fix gatsby-config, use new template for .env.development.local

---

.changeset/nervous-cats-flow.md
.changeset/strong-planets-add.md
packages/decoupled-kit-health-check/__mocks__/server/wordpress/requestHandlers.ts
packages/decoupled-kit-health-check/__tests__/GatsbyWordPressHealthCheck.test.ts
packages/decoupled-kit-health-check/__tests__/NextDrupalHealthCheck.test.ts
packages/decoupled-kit-health-check/__tests__/__snapshots__/GatsbyWordPressHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/__tests__/__snapshots__/NextDrupalHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/__tests__/__snapshots__/NextWordPressHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/src/bin.ts
packages/decoupled-kit-health-check/src/classes/GatsbyWordPressHealthCheck.ts
packages/decoupled-kit-health-check/src/classes/errors.ts

- Add GatsbyWordPressHealthCheck
- Add tests for GatsbyWPHC
- Fix incorrect snapshot test output for the NextWP and NextDrupal healthchecks
- Add changeset, fix a changeset
dkhc (decoupled-kit-health-check)
tested locally and with new test suite

DB-6451: Gatsby + WP health check

---

.changeset/little-feet-drop.md
.changeset/nervous-peas-suffer.md
.changeset/spicy-schools-love.md
packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.ts

Adds the gatsby-wp healthcheck to the gatsby-wp starter and cleans up some changesets.
cli gatsby-wp templates
locally

DB-6451: [gatsby-wp] Add health-check to gatsby starter

---

.changeset/big-points-sniff.md
.changeset/long-ducks-scream.md
packages/decoupled-kit-health-check/package.json
packages/decoupled-kit-health-check/src/bin.ts
pnpm-lock.yaml

@wjcheng1 noted that this fails on node <18, but we should still support node 14-16 because builds may still happen on those versions on the platform.
This should allow the health check scripts to run on node <18
dkhc (decoupled-kit-health-check)
tested locally with `pnpm env use 14 --global`

[dkhc] Support node >=14

---

.changeset/calm-rings-shake.md
.changeset/young-bats-collect.md
packages/decoupled-kit-health-check/__tests__/__snapshots__/GatsbyWordPressHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/__tests__/__snapshots__/NextDrupalHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/__tests__/__snapshots__/NextWordPressHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/src/classes/GatsbyWordPressHealthCheck.ts
packages/decoupled-kit-health-check/src/classes/NextDrupalHealthCheck.ts
packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts

Ensures that .env.development.local or .env is read if `NODE_ENV !== 'production'`
dkhc
locally

[dkhc] Ensure env vars are loaded in non-prod envs

---

web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-cache-control-header.md

Adjusted some (what I think are) typos in the Next WP docs.
In the Next WP setting cache control document.
`web/docs/Frontend Starters/Next.js/Next.js + Wordpress/setting-cache-control-header.md`
n/a
@FoxBuru  and I were trying to troubleshoot some cache header behavior, and were using the [documentation here](https://decoupledkit.pantheon.io/docs/frontend-starters/nextjs/nextjs-wordpress/setting-cache-control-headers) to set `Cache-Control`. We noticed that the docs reference `setEdgeHeaders` but in the code this appears to be `setEdgeHeader`.
It's a small enough deal that I thought we'd just file a neighborly PR.  Apologies in advance if I'm mucking something up, and let me know if you'd rather I go through more procedural channels for stuff like this in the future.
Don't forget to [add …

[docs] fixing typo in wp next documentation

---

.changeset/calm-apricots-relate.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/examples/pagination/[[...page]].jsx
packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/examples/pagination/pagination.module.css

- Ensure the pagination example does not fail the entire build in case the `dev-ds-demo` backend with the mock data can not be reached
- In case there is no data, show a message indicating why
cli > templates > `next-drupal`
locally!
I considered doing all 3 starters at once with some template magic but noticed the next-drupal starter is using `getStaticPaths + getStaticProps` instead of `getServerSideProps`. There is a comment indicating why: 
```
// Using getStaticProps here with ISR will have a substantial impact on
// performance due to the large payload.
``` 
but maybe it's time to reconsider?
@backlineint @mitchellmarkoff any thoughts on this? Should we keep on using ISR here even though it's not quite hooked up, or switch to SSR?
Don't forget to [add a …

DB-6265: [next-drupal] pagination example fails gracefully

---

.changeset/itchy-shrimps-check.md
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/gatsby-node.ts
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/createPaginationExamplePage.ts
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/paginationPostsQuery.ts
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/pagination.module.css
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/pagination.module.css.d.ts
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/paginationExample.tsx

gatsby-wp starter fails gracefully if pagination mock data is unavailable
cli > templates > `gatsby-wp`
locally

DB-6588: [gatsby-wp] pagination fails gracefully

---

web/docs/Backend Starters/Decoupled WordPress/add-ons.md
web/docs/Backend Starters/Decoupled WordPress/configuring-build-hooks.md
web/docs/Backend Starters/Decoupled WordPress/configuring-preview-site.md

Added 'Configuring a Preview Site' entry under WP BE Section
Ran docs site manually.

DB-5857: [docs] Add 'Configuring a Preview Site' entry under WP BE Section

---

.changeset/eleven-coins-dance.md
packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md
web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md

Update readme and troubleshooting for gatsby-wordpress regarding how to disable the decoupled-kit-health-check
cli > templates > gatsby-wp & docs

Update troubleshooting in docs and readme re: dkhc

---

.changeset/tiny-kangaroos-yawn.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...searchAlias]].jsx

- `BACKEND_URL` is no longer required to be set for search to work.
- `next-drupal-search-api-addon`
I created a new front end site with this fix applied and was able to get working search when building against a CMS backend with search enabled on our dashboard. I saw successful searches with no BACKEND_URL configured.

DB-6634: `BACKEND_URL` not required for search

---

.changeset/five-news-train.md
.changeset/nice-candles-unite.md
packages/decoupled-kit-health-check/__tests__/GatsbyWordPressHealthCheck.test.ts
packages/decoupled-kit-health-check/__tests__/NextWordPressHealthCheck.test.ts
packages/decoupled-kit-health-check/src/classes/GatsbyWordPressHealthCheck.ts
packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts

Handle a potential trailing slash on the `WPGRAPHQL_URL`
`decoupled-kit-health-check`
locally, new tests added for the affected classes

DB-6644: Fix trailing slash fails health check for WP based starters

---

.github/workflows/canary-release.yml
.github/workflows/release-and-split.yml

prevent the changeset action from setting the git user. My theory is that when the action sets the git user to the action bot, our repo sees that user as not having access to the repo and it fails with a 403.
If we don't set that user, github should see the user as the service account which does have proper permissions and it will work 🤞.

CI: Attempt to fix changeset action

---

.changeset/five-news-train.md
.changeset/nice-candles-unite.md
packages/decoupled-kit-health-check/__tests__/GatsbyWordPressHealthCheck.test.ts
packages/decoupled-kit-health-check/__tests__/NextWordPressHealthCheck.test.ts
packages/decoupled-kit-health-check/src/classes/GatsbyWordPressHealthCheck.ts
packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts

Reverts pantheon-systems/decoupled-kit-js#837
Restoring the previously reverted commit.

Revert "Revert "DB-6644: Fix trailing slash fails health check for WP based s…"

---

.changeset/brown-countries-prove.md
packages/create-pantheon-decoupled-kit/src/templates/partials/shared/readme/sharedReadme.ts

GitHub only supports a few HTML elements, so the style tag for the image wasn't working as intended.
This change should center the logo and use the proper color based on the user's system theme (light/dark)
https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/

DB-6235: Use logo based on system theme (dark/light)

---

.changeset/grumpy-boxes-unite.md
.changeset/mighty-keys-repeat.md
packages/decoupled-kit-health-check/__mocks__/server/drupal/requestHandlers.ts
packages/decoupled-kit-health-check/__mocks__/server/wordpress/requestHandlers.ts
packages/decoupled-kit-health-check/__tests__/NextDrupalHealthCheck.test.ts
packages/decoupled-kit-health-check/__tests__/__snapshots__/NextDrupalHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/package.json
packages/decoupled-kit-health-check/src/classes/NextDrupalHealthCheck.ts
pnpm-lock.yaml

Fix false negatives for the decoupled-router module in the NextDrupalHealthCheck
Added a console.log to indicate the decoupled-router check is in progress similar to the other checks.
dkhc
Tested locally with a valid site and invalid site. I modified the script a bit to skip the Menu check for the valid site.
Test was added to mock a site with valid JSONAPI endpoint and decoupled menu endpoint, but an invalid decoupled router.

DB-6705: Fix Drupal decoupled-router validation

---

.changeset/tall-garlics-suffer.md
packages/create-pantheon-decoupled-kit/src/templates/next-wp/next.config.js

Previously, if a site has the `WPGRAPHQL_URL` set with a trailing slash, the next.config would not properly remove the `/wp/graphql` portion of the URL to set the `IMAGE_DOMAIN`.
This behavior has now been fixed.
`next-wp` cli templates
tested locally

DB-6728: Fix next-wp trailing slash in WPGRAPHQL_URL breaks IMAGE_DOMAIN

---

pnpm-lock.yaml
web/docs/Backend Starters/Decoupled Drupal/creating-new-project.mdx
web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
web/docs/Backend Starters/terminus-decoupled-kit-plugin.md
web/docs/decoupled-kit-overview.mdx
web/docs/pantheon-front-end-sites.md
web/docusaurus.config.js
web/package.json
web/src/css/custom.css
web/src/theme/Admonition/index.js
web/src/theme/Admonition/styles.module.css

- Added a shiny admonition to call out Pantheon specific documentation. I think there is a reality where we need to be able to mention the platform and our docs cannot be 100% agnostic as much as we'd like them to be. This will help call out these docs/sections so that it is clear that they are intended for use in that context.
- revised a few docs to use the new admonition.
- Added git clone instructions for the decoupled upstreams on the 'creating a new drupal/wp project' docs.
docs. Swizzled the Admonitions to add the new one. Added the relevant custom CSS as well.
ran docs site locally
This guide was very helpful especially for the CSS part: https://docusaurus.community/knowledge/component-library/existing/Admonitions/
Don't forget to [add a …

DB-4833: specify platform docs

---

packages/create-pantheon-decoupled-kit/src/types.ts

I'm not sure why this didn't show up in my IDE when I was working on it the first time and I had a feeling this was wrong; The versions should be available to the templates/`Input` type but not required in the `BaseGeneratorData` type.
This shouldn't require a changeset, it will be picked up in the next one or the main release..
cli types
ESLint is no longer throwing errors in the tagged templates for the pkg versions

Make all PackageVersionData keys optional only on BaseGeneratorData

---

package.json
pnpm-lock.yaml
web/.eslintrc
web/package.json

Use the published eslint config to fix failing build
Most recent build of the docs site failed due to the workspace eslint config missing from the npm registry. This change should allow the site to build again.

DB-6721: Use published eslint-config for docs site

---

.changeset/good-fans-invent.md
.changeset/yellow-gorillas-jump.md
packages/decoupled-kit-health-check/README.md
packages/decoupled-kit-health-check/__tests__/__snapshots__/GatsbyWordPressHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/__tests__/__snapshots__/NextDrupalHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/__tests__/__snapshots__/NextWordPressHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/__tests__/noDKHC.test.ts
packages/decoupled-kit-health-check/src/bin.ts
packages/decoupled-kit-health-check/src/classes/NextDrupalHealthCheck.ts
packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts
packages/decoupled-kit-health-check/src/classes/errors.ts
packages/decoupled-kit-health-check/src/utils/logger.ts
web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md
web/docs/Frontend Starters/Next.js/Next.js + Drupal/troubleshooting.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md

- health check will be skipped if `NO_DKHC` env var is set
- refined some of the prefix glyphs in the health check messages
- updated readme and docs for removing/opting out of the health check
`dkhc`, docs
locally

DB-6765: Opt out health check with an env var

---

web/src/pages/docs/decoupled-kit-overview.jsx

Should fix the 404 from our old homepage (https://decoupledkit.pantheon.io/docs/decoupled-kit-overview)
docs
locally

Add a redirect to the previous front page to current

---

.changeset/bright-bottles-end.md
.changeset/nasty-spoons-attack.md
packages/drupal-kit/src/lib/defaultFetch.ts
packages/wordpress-kit/__mocks__/server/basicPostsQuery.ts
packages/wordpress-kit/src/lib/GraphQLClientFactory.ts
web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md

Mostly just `%s/Fastly-Debug/Pantheon-Skey`.
Added the `:::pantheon` admonition to the Mermaid diagrams on those pages too. Is the copy ok here?
`wordpress-kit`, `drupal-kit`
Tested by locally symlinking new build of the packages to starter kits and running them locally. Editing the content and refreshing shows the new edit.

DB-6775: Use Pantheon-SKey to obtain surrogate key header

---

web/docs/Backend Starters/Decoupled Drupal/add-ons.md
web/docs/Backend Starters/Decoupled Drupal/caching-considerations.md
web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md
web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md
web/docs/Backend Starters/Decoupled Drupal/creating-a-new-project.mdx
web/docs/Backend Starters/Decoupled Drupal/local-development.md
web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md
web/docs/Backend Starters/Decoupled WordPress/configuring-existing-project.md
web/docs/Backend Starters/Decoupled WordPress/local-development.md
web/docs/Backend Starters/terminus-decoupled-kit-plugin.md
web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
web/docs/decoupled-kit-overview.mdx

Changed to use the term 'backend' in all cases.
Use the term 'frontend' unless the context is the Front-end Sites product.
There was some Slack discussion if this is the correct language long term. I think this change still makes sense as it is small in scope, provides consistency, and doesn't change any URL slugs. We can change again if necessary, and we can account for having to handle redirects and updating dependent links in the estimate.
Docs md/mdx files.
Reviewing docs site locally.

DB-5856: [docs] Audit uses of back-end and front-end for consistency

---

.github/workflows/canary-release.yml
.github/workflows/release-and-split.yml

Missed a few yaml files for the updated pnpm version. I'm not 100% sure if this will fix the [latest CI issue](https://github.com/pantheon-systems/decoupled-kit-js/actions/runs/6332095178/job/17197940888) but it's a start!
`pnpm i` said everything was up to date.

Use pnpm 8.8.0 for all workflows

---

.github/templates/emtpy-package.json
.github/workflows/canary-sites-split.yml
packages/react-kit/package.json

Since the `react-kit` is a package, we use some workspace configs that are not available in the build container after the repo is split to its mirror. As a workaround, the action now takes `build` and `out_path` vars in the matrix. If build exists it will run `build-storybook` for the package and copy the artifact to `./storybook/{package name}` along with an empty package.json which is necessary for the build container, even if it is not doing the build.
canary-sites-split workflow
Tested by running the commands locally and deploying the result to FES.

KIT-46: Fix react-kit storybook deployment

---

.github/actions/setup-node/action.yml
.github/workflows/canary-sites-split.yml

Add a composite action that will setup node, and pnpm if the flag is true.
We should update other actions to use this so we only have to update node and pnpm versions in one spot for our actions, it's easy to miss a file.
CI

KIT-46: Setup pnpm if building storybook

---

.changeset/eight-lamps-yawn.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.ts
packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.ts
packages/nextjs-kit/package.json
packages/nextjs-kit/src/components/contentWithImage.tsx
packages/nextjs-kit/src/components/recipe.tsx
pnpm-lock.yaml

- Updates nextjs-kit and the starters to 13.5.6.
- Includes workaround for `<Image />` component outlined [here](https://github.com/colbyfayock/next-cloudinary/pull/229).
Locally.

KIT-97: Upgrade to NextJs `v13.5.6`

---

.github/workflows/cli-addon-tests.yml
README.md

- Add slack notification step to the cli add-on regression test workflow
- Fix the upload path for the playwright test result
- Added badges for the GitHub actions to the README
ci-addon-tests workflow, README
Tested the blocks in the [slack block builder](https://app.slack.com/block-kit-builder)

KIT-67: Add slack notification to add-on regression test workflow

---

ci-tests/package.json
ci-tests/playwright.config.ts

The playwright trace was not being generated.
Also added `playwright` to the `ci-tests` workspace to be able to run things like `pnpm -F ci-tests playwright show-report if the report is in the `ci-tests/playwright-report` dir.
`ci-tests` workspace

KIT-67: Add playwright config to generate report

---

.github/workflows/snapshot-release.yml
configs/prettier.config.js

Added a new GitHub Action workflow that does a snapshot release on push or PR to any feat/* branch. It should take the branch name as the tag name.
We may want an action in the future that cleans up snapshots older than X months but for now I don't think it's necessary.
https://github.com/apollographql/apollo-client/blob/main/.github/workflows/snapshot-release.yml#L73C11-L79 was very helpful in writing this.
CI
Tested some of the commands locally and asked CoPilot for some help, accuracy on that is TBD
Tried to add a check to make sure the submitter is part of the team to prevent unauthorized access to the releases.

KIT-126: Setup snapshot releases for `feat/*`

---

.github/workflows/snapshot-release.yml

Action failed on permissions, looks like the env var name was incorrect. Also looks like the var did not expand as expected in the slack message so fixing that also.

KIT-126: Fix env var name

---

.github/workflows/snapshot-release.yml

Use the team name instead of the slug. Docs on the action were not clear which to use but since it failed with the slug I'm guessing this is the fix.
Should we use an action env var here instead?

KIT-126: Use team name instead of slug

---

.changeset/tender-geckos-smash.md
packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/api/preview.js

- Prevents refresh and clears the `access_token` if `test=true` in the preview route.
Locally

KIT-111: Prevent Caching In Test Preview Route

---

.github/workflows/snapshot-release.yml

Build the CLI after running the version command so that the CLI has any snapshot versions it needs in the templates.

KIT-126: Build after version to get proper deps versions in CLI

---

packages/decoupled-kit-health-check/__tests__/GatsbyWordPressHealthCheck.test.ts
packages/decoupled-kit-health-check/__tests__/__snapshots__/GatsbyWordPressHealthCheck.test.ts.snap
packages/decoupled-kit-health-check/src/classes/GatsbyWordPressHealthCheck.ts

Health check will not fail if CMS is http but will fail if no protocol is set.
`decoupled-kit-health-check`
locally
Test steps can be found in the comments of the related ticket.

KIT-63: Adjust Gatsby Health Check Environment Variable Valid Protocol

---

.changeset/calm-countries-roll.md
packages/create-pantheon-decoupled-kit/src/templates/tailwind-shared/tailwind.config.cjs.hbs

- Fix the tailwindcss config for gatsby so that it does not force an infinite re-render in dev mode due to the `d.ts` files
`cli` templates.

KIT-142: Fix gatsby develop infinite re-render

---

.circleci/config.yml
.github/workflows/run-tests.yml
README.md
pnpm-lock.yaml

First step towards removing CircleCI and adopting Dependabot for this repo.
We may need to adjust the branch rules regarding the CircleCI check.
- Remove test job from circleci config
- Add new GitHub Action workflow to run the tests on push to any branch
- Do we want to lock this down to PRs or certain branches?

KIT-173: Use GHA instead of CircleCI for test job

---

.github/workflows/canary-release.yml
.github/workflows/release-and-split.yml

Another attempt at fixing the test workflow not running on the changesets branch.
https://github.com/changesets/action/issues/70 this thread points to turning off persisted credentials as a solution. I don't think it will but there is a chance the split action might fail due to this, worth keeping an eye on it.
changeset actions

Do not persist credentials for release checkouts

---

.github/workflows/canary-release.yml
.github/workflows/release-and-split.yml

We tried this before but it didn't work by itself. Maybe with the `persist-credentials: false` and this setting, workflows will properly run on the changeset branch?
release actions

Try checkout with token to enable workflows on changeset branches

---

.github/workflows/canary-release.yml
.github/workflows/release-and-split.yml

This is my last idea. I see the new code scanning workflows are running on the changeset branch, so I'm still unclear on why the test workflow isn't being triggered.

Do not set git user in changeset action

---

.circleci/config.yml
.github/dependabot.yml

Added .dependabot.yml
Removed the audit job from .circleci.yml
We should be able to remove the `CIRCLECI_AUDIT_PR_TOKEN` envar from circle when this is merged.

KIT-137: Create dependabot.yml

---

.github/workflows/release-and-split.yml

Remove `setupGitUser` from the release workflow.

Remove setupgituser

---

packages/nextjs-kit/__tests__/snapshotTests/__snapshots__/footer.test.tsx.snap

Need to update the snapshot for the new year. This should trigger the cli-addon regression tests to create a new PR with updated snapshots as well since those have been failing since the copy year changed over.
Update nextjs-kit snapshot tests

Update snapshots for 2024

---

packages/create-pantheon-decoupled-kit/__tests__/fixtures/runESLint/withLint/package.json
packages/create-pantheon-decoupled-kit/__tests__/fixtures/runESLint/withLintFix/package.json
packages/create-pantheon-decoupled-kit/__tests__/fixtures/runESLint/withoutLint/package.json
packages/create-pantheon-decoupled-kit/vite.config.mts

These were causing false positives for dependabot. They aren't necessary for our tests.
Changed the vitest coverage.all option to flase
Forgot that forks don't work anymore. Supersedes #1108 

Remove deps from test fixtures
